### ISSUE TITLE
address id怎么抓包获取呢

### ISSUE THREAD

**Issue by albertszg** [Ljzd-PRO/Mys_Goods_Tool#1]

**Comment by Ljzd-PRO** [comment]
抓包：我的-设置-通行证账号与安全-管理收货地址 这个页面

**Comment by Ljzd-PRO** [comment]
点击 我的-设置-通行证账号与安全-管理收货地址 会触发：
GET请求 URL: `https://api-takumi.mihoyo.com/account/address/list?t=1635930737638`
在响应数据中的`"id"`即为`Address_ID`。
如果有多个地址的话，会有多个`"id"`，选择你要使用的那个。

**Comment by albertszg** [comment]
感谢，之前找到了id了，已经换了抱枕，完美



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月5日(周日) 晚上10:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Ljzd-PRO/Mys_Goods_Tool] address id怎么抓包获取呢 (Issue #1)




 
点击 我的-设置-通行证账号与安全-管理收货地址 会触发：
 GET请求 URL: https://api-takumi.mihoyo.com/account/address/list?t=1635930737638
 在响应数据中的"id"即为Address_ID。
 如果有多个地址的话，会有多个"id"，选择你要使用的那个。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Fnvelope** [comment]
> 

请问这个id是X-Trace-Id吗

**Comment by Ljzd-PRO** [comment]
@Fnvelope 不是。当打开米游社App中 我的-设置-通行证账号与安全-管理收货地址 这个页面的时候，App会发出一个GET请求，请求URL为`https://api-takumi.mihoyo.com/account/address/list?t=1635930737638 `，这个GET请求的返回数据中有`id`键，`id`对应的值就是配置文件里的`Address_ID`
GET请求返回例子：
```
{
  "retcode": 0,
  "message": "OK",
  "data": {
    "list": [
      {
        "id": "12345",
        "connect_name": "小王",
        "connect_areacode": "+86",
        "connect_mobile": "189****9999",
        "country": 1,
        "province": xxxxxx,
        "city": xxxxx,
        "county": xxxxxx,
        "province_name": "某省",
        "city_name": "某市",
        "county_name": "某区",
        "addr_ext": "某路某号",
        "is_default": 0,
        "status": 1
      },
      {
        "id": "67890",
        "connect_name": "小王",
        "connect_areacode": "+86",
        "connect_mobile": "189****9999",
        "country": 1,
        "province": xxxxxx,
        "city": xxxxx,
        "county": xxxxxx,
        "province_name": "某某省",
        "city_name": "某某市",
        "county_name": "某某区",
        "addr_ext": "某某路某某号",
        "is_default": 0,
        "status": 1
      }
    ]
  }
}
```
在这个例子中，`12345`和`67890`就是可选用的Address_ID，兑换的周边要寄送到哪个地址配置文件就填哪个

**Comment by Ljzd-PRO** [comment]
已经添加说明文档：https://github.com/Ljzd-PRO/Mys_Goods_Tool/blob/main/Docs/Address_ID.md
