### ISSUE TITLE
RuntimeWarning: coroutine 'exchange_begin' was never awaited

### ISSUE THREAD

**Issue by cwhcwh89766** [Ljzd-PRO/Mys_Goods_Tool#101]
![2@$HWW{UFG(J8M GD$GUW7](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/59152997/a6c43750-9795-4356-83aa-c1b83b366860)

用的是打包后的exe工具

**Comment by Ljzd-PRO** [comment]
与 #98 情况相同
