### ISSUE TITLE
debian运行出错 No module named 'uvloop'

### ISSUE THREAD

**Issue by ytgo** [Ljzd-PRO/Mys_Goods_Tool#103]
![49212d1d23da37023ab522b68f61da6](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/39256100/daeb9690-efb4-4eba-9e56-5fa5a6ab1761)

**Comment by Ljzd-PRO** [comment]
试一下`sudo apt install python3-uvloop`

**Comment by ytgo** [comment]
安装后可以了 谢谢
