### ISSUE TITLE
完成人机验证后，卡在发送验证码阶段

### ISSUE THREAD

**Issue by RemKeeper** [Ljzd-PRO/Mys_Goods_Tool#105]
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/78486275/cc6f211b-3873-43b0-80a0-cd94428dbe37)
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/78486275/965686d3-5380-4723-8113-565ba562abba)
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/78486275/71b9f8ca-4d46-47b1-911c-9cc7e02cf2f6)

**Comment by VoidImagination** [comment]
同 我也卡在这了

**Comment by handlerSam** [comment]
同 我也是

**Comment by Ljzd-PRO** [comment]
调试了一下，服务器返回了
```json
{"code":200,"data":{"info":"MMT validate Failed","msg":"图片验证码失败","status":-302}}
```
之前就有注意到米哈游通行证登录页的人机验证从极验第三代改成了第四代，有可能是现在开始mhy服务器不再接受第三代的验证结果

**Comment by Ljzd-PRO** [comment]
暂时可以到 https://user.mihoyo.com/#/login/captcha 获取验证码，但是不在网页上登录，而是把验证码填入程序登录表单进行登录，就像之前v1那样

**Comment by Ljzd-PRO** [comment]
> 调试了一下，服务器返回了
> 
> ```json
> {"code":200,"data":{"info":"MMT validate Failed","msg":"图片验证码失败","status":-302}}
> ```
> 
> 之前就有注意到米哈游通行证登录页的人机验证从极验第三代改成了第四代，有可能是现在开始mhy服务器不再接受第三代的验证结果

更新到第四代以后还是一样，但浏览器里就可以，挺奇怪的。

**Comment by Ljzd-PRO** [comment]
已更新：https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v2.0.5
