### ISSUE TITLE
多少ms才能抢到好东西，比如小米的耳机，我 30-45ms抢不到

### ISSUE THREAD

**Issue by xinjioakanai** [Ljzd-PRO/Mys_Goods_Tool#106]

**Comment by xinjioakanai** [comment]
这种要5ms甚至1ms才能抢到吗

**Comment by Ljzd-PRO** [comment]
可以修改 user_data.json 里的 exchange_latency 为0，让兑换不再额外产生延时。
https://github.com/Ljzd-PRO/Mys_Goods_Tool/blob/0a3acfeb433a7ec2c1d70edb9d59000d562753fb/mys_goods_tool/user_data.py#L313

**Comment by Wangxy3** [comment]
我昨天是20ms，三个号都抢到毛绒团子了

**Comment by xinjioakanai** [comment]
感谢，我试试
