### ISSUE TITLE
运行exe十秒左右报错TypeError:'NoneType'object is not iterable 并闪退

### ISSUE THREAD

**Issue by A7424** [Ljzd-PRO/Mys_Goods_Tool#107]
![R8 AQ 7Z53T{SPPW5GP$4FQ](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/103619507/f3d51a46-8377-4e79-bcc4-e31919c4e48c)
版本是2.0.3

**Comment by Ljzd-PRO** [comment]
#108

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/5021310785
等待构建完成就可以下载修复后的程序。

**Comment by A7424** [comment]
> https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/5021310785 等待构建完成就可以下载修复后的程序。

已解决，可以打开了

**Comment by xinjioakanai** [comment]
> https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/5021310785 等待构建完成就可以下载修复后的程序。

我的也是这样，怎么解决，我没看懂什么意思

**Comment by xinjioakanai** [comment]
> https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/5021310785 等待构建完成就可以下载修复后的程序。

要等下次更新吗

**Comment by Ljzd-PRO** [comment]
> > https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/5021310785 等待构建完成就可以下载修复后的程序。
> 
> 要等下次更新吗

链接进去以后就可以下载修复后的程序了。每次代码修改都会自动生成可执行程序，但是需要一定时间

**Comment by xinjioakanai** [comment]
> > > https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/5021310785 等待构建完成就可以下载修复后的程序。
> > 
> > 
> > 要等下次更新吗
> 
> 链接进去以后就可以下载修复后的程序了。每次代码修改都会自动生成可执行程序，但是需要一定时间

谢了，我看到了，上次没看到下面的下载链接
