### ISSUE TITLE
在启动后软件崩溃

### ISSUE THREAD

**Issue by DancingSnow0517** [Ljzd-PRO/Mys_Goods_Tool#108]
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/60736156/af5465d5-320f-4624-af2e-b2c1f89defb9)
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/60736156/ab6b3be2-6ad7-4268-bdf9-662732025eb4)
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/60736156/becf020e-8f9c-48b2-ba22-b00c8a8a11c5)
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/60736156/4a3cf963-a58d-4336-8164-7400c4b3f197)

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/5021310785
等待构建完成就可以下载修复后的程序。

**Comment by TianXiaSky** [comment]
> https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/5021310785 等待构建完成就可以下载修复后的程序。

上周五定时兑换后，发现没兑换，原来有更新
这周用了最新版本应该没问题了吧，希望能抢点周边
