### ISSUE TITLE
用米游社页面登陆的验证码显示网络连接失败

### ISSUE THREAD

**Issue by lzh19999** [Ljzd-PRO/Mys_Goods_Tool#115]
用米游社页面登陆的验证码显示网络连接失败
![1685702602107](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/118620347/047958cd-c60b-42a4-9840-38df155d8e7a)

**Comment by Ljzd-PRO** [comment]
看一下日志文件

**Comment by lzh19999** [comment]
![1685712330610](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/118620347/9bcfee45-39ae-4933-99e3-af6fa8fe2812)

**Comment by Ljzd-PRO** [comment]
目前发送短信验证码应该也是无法使用的，因为米哈游升级到了gt4，可以参考 [常见问题](https://github.com/Ljzd-PRO/Mys_Goods_Tool/wiki/Troubleshooting#人机验证完成后-发送短信验证码失败-或-卡在加载中)，在官网发送短信验证码，然后验证码填入程序里

**Comment by Ljzd-PRO** [comment]
类似 #105 的情况

**Comment by lzh19999** [comment]
是的，我是人机验证完之后没有收到验证码，然后在官网发送短信验证码，手机收到了之后填到程序里显示网络连接失败。是因为我在海外吗，我也开加速器试过，也显示失败。

**Comment by Ljzd-PRO** [comment]
可能和Option请求有关，看上去不是米游社API的问题

**Comment by lzh19999** [comment]
嗯嗯我换个电脑试试吧

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/5156199244
可以在这里下载刚才修复后自动构建的程序

**Comment by lzh19999** [comment]
下载了试了一下还是不行，换了台电脑也不行T_T
![屏幕截图 2023-06-02 234528](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/118620347/493fad62-c61a-4927-9ec1-bbe19cb9e37d)
![屏幕截图 2023-06-02 234556](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/118620347/0d30e794-dec5-41ef-a4d7-f684c40ab7f7)

**Comment by Ljzd-PRO** [comment]
商品列表可以正常获取吗

**Comment by lzh19999** [comment]
可以的
![1685792822144](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/118620347/a9fb2a8c-c997-4a11-a7b0-a94569190ec0)

**Comment by lzh19999** [comment]
可以用之前的无图形界面版本获取cookie那些信息后在图形界面登录吗，之前的都还能用

**Comment by Ljzd-PRO** [comment]
> 可以用之前的无图形界面版本获取cookie那些信息后在图形界面登录吗，之前的都还能用

可以手动填入cookies数据到用户数据文件，如果熟悉JSON的话应该不难的。也打算之后加一个手动导入Cookies

**Comment by lzh19999** [comment]
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/118620347/ee47d61d-be91-4c21-9c92-6792af5ebfde)
我试着写了一下，这个account部分没绑定的时候是空的，格式不知道怎么写，这样写了一下程序打不开😂

**Comment by palxex** [comment]
一样程序内无法发送短信、手动在网页发短信回到程序登录提示网络连接失败。参照代码尝试手写json会在加载时直接崩溃，提示看不懂，同请求给出示例json。
尝试的写法：
```
...
"accounts":{
  "test_user":{
    "phone_number":"xxxx",
    "cookies":{"stuid":"xxxx","stoken":"v2_xxxx","cookie_token":"xxxx"}
  }
}
...
```

**Comment by Ljzd-PRO** [comment]
一个包含两个账号的 `user_data.json` 参考：
- `12345678`, `23456789` 是 米游社UID
- `device_id_xxx` 是一串GUID，对应 ~~Cookies~~ Headers里的 `x-rpc-device_id`
```json
{
    "version": "xxx",
    "exchange_plans": [],
    "preference": {
        "...": "..."
    },
    "salt_config": {
        "xxx": "xxx"
    },
    "device_config": {
        "xxx": "xxx"
    },
    "accounts": {
        "12345678": {
            "phone_number": "11122223333",
            "cookies": {
                "stuid": "12345678",
                "ltuid": "12345678",
                "account_id": "12345678",
                "login_uid": "12345678",
                "stoken_v1": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "stoken_v2": "XXXXXXXXXXXXXX-XXXX-xxxxxxxxxxxxxxx-XXXXXXXXXXXXXX-xxxxxxxxxxxx",
                "cookie_token": "XXXXXXXXXXXXXXXXXX",
                "login_ticket": "XXXXXXXXXXXXXXXXXXXXX",
                "ltoken": "XXXXXXXXXXX",
                "mid": "XXXXX"
            },
            "device_id_ios": "971DA214-XXXX-XXXX-XXXX-B6A8319EF40E",
            "device_id_android": "E5AD4629-XXXX-XXXX-XXXX-6470801F5C0A"
        },
        "23456789": {
            "phone_number": "22233334444",
            "cookies": {
                "stuid": "23456789",
                "ltuid": "23456789",
                "account_id": "23456789",
                "login_uid": "23456789",
                "stoken_v1": "xxxxxxxxxxxxxxx",
                "stoken_v2": "XXXXXXXXXXX-xxxxxxxx-XXXXXXXXX-xxxxxxxxxxxxxx",
                "cookie_token": "XXXXXXXXXXXXXXXX",
                "login_ticket": "xxxxxxxxxxxxxxxxxx",
                "ltoken": "XXXXXXXXXXXXX",
                "mid": "xxxxxxxxxxxxxxx"
            },
            "device_id_ios": "082D0890-XXXX-XXXX-XXXX-D1A36FBC6709",
            "device_id_android": "26143EEE-XXXX-XXXX-XXXX-D180143BD07C"
        }
    }
}
```

**Comment by Ljzd-PRO** [comment]
`stoken_v2` 和 `mid` 可以不填入

**Comment by Ljzd-PRO** [comment]
刚才我尝试了一下 2.0.4 的Windows版本，是可以正常登陆的。不清楚是不是UI方面有点Bug。

可以尝试直接在手机号输入框填写手机号，然后**不要点击获取验证码**，直接去通信证页面发送验证码，**不在网页上使用验证码**，然后把收到的验证码填入程序验证码输入框，点击登陆。

**Comment by palxex** [comment]
原来如此。之前测试都是填手机号，点发送，失败后再去网页端发送的。改为您的步骤后已成功。

**Comment by lzh19999** [comment]
按格式写了account可以打开程序并且绑定了账号，但是之前无图形界面好像没有返回x-rpc-device_id，所以没有没填device_id_xxx，不知道有没有影响，测试了一个还没开始兑换的商品返回库存不足，是正常的吗？
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/118620347/4f15ca04-8009-47cc-9925-a683788867ce)

![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/118620347/3835af96-4838-4714-8390-65e85d557f36)

**Comment by Ljzd-PRO** [comment]
> 按格式写了account可以打开程序并且绑定了账号，但是之前无图形界面好像没有返回x-rpc-device_id，所以没有没填device_id_xxx，不知道有没有影响，测试了一个还没开始兑换的商品返回库存不足，是正常的吗？ ![image](https://user-images.githubusercontent.com/118620347/243161241-4f15ca04-8009-47cc-9925-a683788867ce.png)
> 
> ![image](https://user-images.githubusercontent.com/118620347/243161238-3835af96-4838-4714-8390-65e85d557f36.png)

库存不足是正常的。然后之前说错了，`x-rpc-device_id`是在Headers里的，是一个Header条目，而不是在Cookies里。没有的话问题也不大，程序看起来也没有出异常。

**Comment by lzh19999** [comment]
嗯嗯，应该是没问题了，非常感谢！！

**Comment by shouyangyan** [comment]
> 刚才我尝试了一下 2.0.4 的Windows版本，是可以正常登陆的。不清楚是不是UI方面有点Bug。
> 
> 可以尝试直接在手机号输入框填写手机号，然后**不要点击获取验证码**，直接去通信证页面发送验证码，**不在网页上使用验证码**，然后把收到的验证码填入程序验证码输入框，点击登陆。

![QQ图片20230616195500](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/75553326/faf065d9-24f3-4fd3-89bb-9243703d81fa)
可是我按这样做了结果是这样的，怎么解决呀？

**Comment by Ljzd-PRO** [comment]
> > 刚才我尝试了一下 2.0.4 的Windows版本，是可以正常登陆的。不清楚是不是UI方面有点Bug。
> > 可以尝试直接在手机号输入框填写手机号，然后**不要点击获取验证码**，直接去通信证页面发送验证码，**不在网页上使用验证码**，然后把收到的验证码填入程序验证码输入框，点击登陆。
> 
> ![QQ图片20230616195500](https://user-images.githubusercontent.com/75553326/246409419-faf065d9-24f3-4fd3-89bb-9243703d81fa.png) 可是我按这样做了结果是这样的，怎么解决呀？

再试试看？之前内置的人机验证发送的短信验证码，偶尔也会提示错误

**Comment by LostWarriorFamg** [comment]
> > > 刚才我尝试了一下 2.0.4 的Windows版本，是可以正常登陆的。不清楚是不是UI方面有点Bug。
> > > 可以尝试直接在手机号输入框填写手机号，然后**不要点击获取验证码**，直接去通信证页面发送验证码，**不在网页上使用验证码**，然后把收到的验证码填入程序验证码输入框，点击登陆。
> > 
> > 
> > ![QQ图片20230616195500](https://user-images.githubusercontent.com/75553326/246409419-faf065d9-24f3-4fd3-89bb-9243703d81fa.png) 可是我按这样做了结果是这样的，怎么解决呀？
> 
> 再试试看？之前内置的人机验证发送的短信验证码，偶尔也会提示错误

刚刚发现只要预先在accounts输入好一个模板，就能顺利导入新账号，否则就会遇到这些错误

**Comment by Ljzd-PRO** [comment]
#126 已修复

**Comment by Yuiffy** [comment]
同样问题

**Comment by Ljzd-PRO** [comment]
应该找到原因了，已修复 https://github.com/Ljzd-PRO/Mys_Goods_Tool/issues/131#issuecomment-1621808146

**Comment by Crace00** [comment]
求大佬解答account模板怎么写啊 后面的cookie_token和login_ticket都应该输什么 天坑专业的对计算机一窍不通
