### ISSUE TITLE
win10双击打开图形化程序，鼠标随便动一下界面上就会出现这样的重影

### ISSUE THREAD

**Issue by Yoimiya-993** [Ljzd-PRO/Mys_Goods_Tool#117]
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/52495231/24f61448-85e8-484f-9994-1926f0df5dc6)

**Comment by Ljzd-PRO** [comment]
Windows 10的默认终端确实不适合显示这种界面，可以尝试在应用商店下载Windows Terminal，和Windows 11用的是同一个

**Comment by Ljzd-PRO** [comment]
之后会增加仅使用键盘控制的简单界面

**Comment by itdengwenbin** [comment]
> 

有用，谢谢大佬

**Comment by Yoimiya-993** [comment]
> Windows 10的默认终端确实不适合显示这种界面，可以尝试在应用商店下载Windows Terminal，和Windows 11用的是同一个

有用，谢谢大佬
