### ISSUE TITLE
我想学习打包这个应用，可是我使用pyinstaller打包后无法运行

### ISSUE THREAD

**Issue by baby1000001000** [Ljzd-PRO/Mys_Goods_Tool#119]
麻烦请教下打包方式，期待回复

**Comment by Ljzd-PRO** [comment]
可以参考 https://github.com/Ljzd-PRO/Mys_Goods_Tool/blob/stable/.github/workflows/build-v2.yml

要先安装需要的一些python包的依赖，然后再打包。
打包是使用 spec 文件读取配置来打包的：
```shell
pyinstaller ./Mys_Goods_Tool.spec
```

**Comment by Ljzd-PRO** [comment]
安装依赖最好是使用 poetry 安装，不行的话就用
```shell
pip install -r requirements.txt
```

**Comment by baby1000001000** [comment]
感谢，我使用pyinstaller 打包就报错了，所以就想学一下
