### ISSUE TITLE
Windows 10 20H2 启动程序失败 Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!

### ISSUE THREAD

**Issue by pbxs666** [Ljzd-PRO/Mys_Goods_Tool#123]
就是这个地址
https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/5316402975

报错截图：
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/47630168/7303ced0-5173-4d9b-813f-5672a8b69202)

测试环境是Windows 10 20H2。我不懂Python，搜了下报错信息，说是打包的问题，我也不懂，但有个帖子说到生成的文件无法在Windows下运行，Ubuntu却可以，我打算先试试Linux下可行不，已经在下Ubuntu的镜像文件了😁

**Comment by Ljzd-PRO** [comment]
确实应该是打包的问题，不过大多Windows可以正常运行，可能和系统版本有点关系。

**Comment by pbxs666** [comment]
> 确实应该是打包的问题，不过大多Windows可以正常运行，可能和系统版本有点关系。

这个应该跟系统无关吧，刚试了下Linux（Ubuntu 22.04.2 LTS），正式发行版2.0.4可以运行，而actions里的版本就不行了
![QQ截图20230621115535](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/47630168/ea87013a-0912-4510-8163-1195d828cd94)

**Comment by beiji-O-o** [comment]
> > 确实应该是打包的问题，​​不过大部分 Windows 可以正常运行，可能和系统版本有些关系。
> 
> 这个应该跟系统无关吧，刚试了下Linux，正式发行版本2.0.4可以运行，而actions里的版本就不行了 ![QQ截图20230621115535](https://user-images.githubusercontent.com/47630168/247391738-ea87013a-0912-4510-8163-1195d828cd94.jpg)

我也是相同问题

**Comment by pbxs666** [comment]
不知道大佬有时间再编译一次不，我想自己动手但就像老虎吃天，不知该如何下口。之前只学过皮毛，根本没用，哈哈。

今天下午7点，刚好有原神的兑换，我也能帮你测试下改了api后是否有效。

这几天一直等发版没等到，所以才去actions里找测试版，结果因打包问题Windows和Ubuntu都运行不了😂，所以才有此冒昧请求，还望见谅。不行的话我下周再试，反正米游社这批货兑换截止到下周

**Comment by pbxs666** [comment]
> 不知道大佬有时间再编译一次不，我想自己动手但就像老虎吃天，不知该如何下口。之前只学过皮毛，根本没用，哈哈。
> 
> 今天下午7点，刚好有原神的兑换，我也能帮你测试下改了api后是否有效。
> 
> 这几天一直等发版没等到，所以才去actions里找测试版，结果因打包问题Windows和Ubuntu都运行不了😂，所以才有此冒昧请求，还望见谅。不行的话我下周再试，反正米游社这批货兑换截止到下周

刚才试了https://github.com/Ljzd-PRO/Mys_Goods_Tool/wiki/Installation
的教程，在Linux下运行成功了，但是好像还是正式发行版2.0.4，现在在想怎么才能编译运行最新提交的版本

**Comment by pbxs666** [comment]
> > 不知道大佬有时间再编译一次不，我想自己动手但就像老虎吃天，不知该如何下口。之前只学过皮毛，根本没用，哈哈。
> > 今天下午7点，刚好有原神的兑换，我也能帮你测试下改了api后是否有效。
> > 这几天一直等发版没等到，所以才去actions里找测试版，结果因打包问题Windows和Ubuntu都运行不了😂，所以才有此冒昧请求，还望见谅。不行的话我下周再试，反正米游社这批货兑换截止到下周
> 
> 刚才试了https://github.com/Ljzd-PRO/Mys_Goods_Tool/wiki/Installation 的教程，在Linux下运行成功了，但是好像还是正式发行版2.0.4，现在在想怎么才能编译运行最新提交的版本

已经成功了🥰，我再试试编译打包成exe，放在Windows下运行。

**Comment by beiji-O-o** [comment]
> > > 不知道大佬有时间再编译一次不，我想自己动手但就像老虎吃天，不知道该怎样下口。之之前只学过皮毛，根本没用，哈哈。今天下午7点，刚好有原神
> > > 的兑换，我也可以帮你测试下修改了api后是否有效。
> > > 这几天一直等开发版没等到，所以才去actions里找测试版，结果因为打包问题Windows和Ubuntu都运行不了😂，所以才有此冒昧请求，还望见谅。不说话我下周再试，反正米游社这批货兑换停止到下周
> > 
> > 
> > 刚试了https://github.com/Ljzd-PRO/Mys_Goods_Tool/wiki/Installation的教程，在Linux下运行成功了，但是好象还是正常开发版2.0.4，现在在想怎么才能编译运行最新提示的版本
> 
> 已经成功了🥰，我再试编译打包成exe，放于Windows下运行。

xd，发个给我呗😂

**Comment by pbxs666** [comment]
@SerPolar 刚恰饭去了，还没好

**Comment by beiji-O-o** [comment]
> @SerPolar刚恰饭去了，还没有好
要是打包了Ubuntu的顺便也发我一份😂，谢谢了

**Comment by pbxs666** [comment]
> > @SerPolar刚恰饭去了，还没有好
> > 要是打包了Ubuntu的顺便也发我一份😂，谢谢了

你可以先试试编译运行，打包估计一时半会搞不定，我才开始学

**Comment by pbxs666** [comment]
> > @SerPolar刚恰饭去了，还没有好
> > 要是打包了Ubuntu的顺便也发我一份😂，谢谢了
Linux版的：
https://wwzg.lanzoum.com/b01ezok5a
密码:9y5q
Windows版的还没搞出来

**Comment by beiji-O-o** [comment]
> 9y5

这个人机验证我过不去😂
我复制不了链接

**Comment by Ljzd-PRO** [comment]
> > 9y5
> 
> 这个人机验证我过不去😂 我复制不了链接

目前内置的人机验证用不了，要手动去登录链接获取验证码

**Comment by Ljzd-PRO** [comment]
可以兑换成功吗，我刚刚就差一点，没赶上时间。

**Comment by beiji-O-o** [comment]
> 

不知道为什么我用腾讯云控制台启动Liunx版的字体会变乱码

**Comment by Ljzd-PRO** [comment]
> 不知道为什么我用腾讯云控制台启动Liunx版的字体会变乱码

腾讯云的网页控制台 终端 对各种符号什么的支持可能不太好，可以在本地电脑配置好兑换计划以后，把用户数据文件复制到服务器，然后加上 `-m exchange-simple` 以无UI的方式直接进入兑换模式，等待兑换。

**Comment by beiji-O-o** [comment]
> > 不知道为什么我用腾讯云控制台启动Liunx版的字体会变乱码
> 
> 腾讯云的网页控制台 终端 对各种符号什么的支持可能不太好，可以在本地电脑配置好兑换计划以后，把用户数据文件复制到服务器，然后加上 `-m exchange-simple` 以无UI的方式直接进入兑换模式，等待兑换。

win环境打不开就是本帖的报错

**Comment by Ljzd-PRO** [comment]
启动程序失败的问题解决了，更新了 pyinstaller 就可以了

**Comment by pbxs666** [comment]
> 可以兑换成功吗，我刚刚就差一点，没赶上时间。

不行，还是一样的报错信息：

06-21 19:00:00 [INFO] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 136508784 商品 2023051611977 兑换失败，可以自行确认。
06-21 19:00:00 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
06-21 19:00:00 [ERROR] mys_goods_tool.exchange_mode | 用户 136508784 - 【原神】2022线上音乐会系列 迷你口琴项链-云堇 - 线程 2 - 兑换失败
06-21 19:00:01 [INFO] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 136508784 商品 2023051611977 兑换失败，可以自行确认。
06-21 19:00:01 [INFO] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 136508784 商品 2023051611977 兑换失败，可以自行确认。
06-21 19:00:01 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
06-21 19:00:01 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
06-21 19:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 136508784 - 【原神】2022线上音乐会系列 迷你口琴项链-云堇 - 线程 3 - 兑换失败
06-21 19:00:01 [INFO] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 136508784 商品 2023051611977 兑换失败，可以自行确认。
06-21 19:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 136508784 - 【原神】2022线上音乐会系列 迷你口琴项链-云堇 - 线程 4 - 兑换失败
06-21 19:00:01 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
06-21 19:00:01 [INFO] mys_goods_tool.api | 米游币商品兑换 - 执行兑换: 用户 136508784 商品 2023051611977 兑换失败，可以自行确认。
06-21 19:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 136508784 - 【原神】2022线上音乐会系列 迷你口琴项链-云堇 - 线程 1 - 兑换失败
06-21 19:00:01 [DEBUG] mys_goods_tool.api | 网络请求返回: {"data":null,"message":"","retcode":1028}
06-21 19:00:01 [ERROR] mys_goods_tool.exchange_mode | 用户 136508784 - 【原神】2022线上音乐会系列 迷你口琴项链-云堇 - 线程 5 - 兑换失败

**Comment by pbxs666** [comment]
> 启动程序失败的问题解决了，更新了 pyinstaller 就可以了

刚我试着在Windows上打包，运行还是闪退，按理说我是今天才安装的pyinstaller，应该是最新版的啊，打包后还是闪退。
不过Linux上打包后倒是可以运行

**Comment by Ljzd-PRO** [comment]
> > 启动程序失败的问题解决了，更新了 pyinstaller 就可以了
> 
> 刚我试着在Windows上打包，运行还是闪退，按理说我是今天才安装的pyinstaller，应该是最新版的啊，打包后还是闪退。 不过Linux上打包后倒是可以运行

可能是因为 `requirements.txt` 和 `pyproject.toml` 里指定了 pyinstaller 版本，刚才我改了 `pyproject.toml`，`requirements.txt` 还没改。可以试试改后自动打包的能不能启动。
