### ISSUE TITLE
添加兑换任务失败

### ISSUE THREAD

**Issue by xmdreamtime** [Ljzd-PRO/Mys_Goods_Tool#140]
添加崩坏：星穹铁道兑换任务后报错闪退，重启直接闪退
╭─────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────╮
│ in _on_mount:1063                                                                                                                                │
│                                                                                                                                                  │
│ in update_data:1048                                                                                                                              │
│                                                                                                                                                  │
│ in append:185                                                                                                                                    │
│                                                                                                                                                  │
│ in mount:765                                                                                                                                     │
│                                                                                                                                                  │
│ in _register:2082                                                                                                                                │
│                                                                                                                                                  │
│ in _register_child:2037                                                                                                                          │
│                                                                                                                                                  │
│ in _append:81                                                                                                                                    │
│                                                                                                                                                  │
│ in _ensure_unique_id:102                                                                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
DuplicateIds: Tried to insert a widget with ID 'list_item-plan_row--8518203362952463957', but a widget
UnClickableItem(id='list_item-plan_row--8518203362952463957') already exists with that ID in this list of children. The children of a widget must
have unique IDs.

**Comment by Ljzd-PRO** [comment]
临时的话可以尝试修改用户数据文件，把里面的兑换计划删掉，再启动。

**Comment by xmdreamtime** [comment]
> 临时的话可以尝试修改用户数据文件，把里面的兑换计划删掉，再启动。

好的，感谢大佬
