### ISSUE TITLE
米游社ip用cmd查的时候一直在变，怎么办？

### ISSUE THREAD

**Issue by mhy289** [Ljzd-PRO/Mys_Goods_Tool#15]

**Comment by Ljzd-PRO** [comment]
`ping`命令？

**Comment by mhy289** [comment]
就是输入 ping bbs.mihoyo.com
然后每过一会，ip就变

**Comment by mhy289** [comment]
![01](https://user-images.githubusercontent.com/91642642/168791937-262c4fde-62c2-4380-b555-73dcd2a210cc.PNG)
![02](https://user-images.githubusercontent.com/91642642/168791948-a706694c-30eb-4a4d-bab1-abaf05bed279.PNG)

**Comment by mhy289** [comment]
情况如上图

**Comment by Ljzd-PRO** [comment]
可能和DNS服务器设置有关，但是应该不影响兑换等操作，因为脚本用的都是域名作为主机名的URL

**Comment by Ljzd-PRO** [comment]
另外兑换的时候用的是`api-takumi.mihoyo.com`

**Comment by mhy289** [comment]
大佬，cookie搞定了，但stoken用网页f12找不到

**Comment by Ljzd-PRO** [comment]
> 大佬，cookie搞定了，但stoken用网页f12找不到

我是用米游社App获取的

**Comment by mhy289** [comment]
> 

米游社不是只有手机有吗，这样的话手机上怎么抓包呢

**Comment by Ljzd-PRO** [comment]
> 米游社不是只有手机有吗，这样的话手机上怎么抓包呢

如果是iOS的话很方便，安卓的话，安卓7以后分为系统信任CA证书和用户信任CA证书，大多App不信任用户添加的证书，要ROOT才能移动证书到系统信任目录，然后抓包，或者反编译App以后修改一个配置文件再重新打包，我现在知道怎么改了，有时间会发出来。当然安卓虚拟机也可以。
