### ISSUE TITLE
貌似解决了1028的问题了

### ISSUE THREAD

**Issue by Aellyt** [Ljzd-PRO/Mys_Goods_Tool#150]
![68DC809B-6804-4DE2-90C9-B4AA070D5BD8](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/83526546/417f880d-3464-492e-ae4f-084caa05cab8)
今天中午跑的，抢到了

**Comment by Ljzd-PRO** [comment]
应该也是比较看运气

**Comment by kuronekoda** [comment]
我昨天抢还是返回1028，抢的是星穹铁道流沙周边

**Comment by dmhfd** [comment]
因为未定没加验证码，原和铁加了
