### ISSUE TITLE
如何构建一个可以在ARM64架构上运行的版本?

### ISSUE THREAD

**Issue by Zmincrix** [Ljzd-PRO/Mys_Goods_Tool#159]
我的服务器是ARM64架构的

**Comment by Ljzd-PRO** [comment]
可以直接用系统的包管理器安装python和pip，然后用pip安装。

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/Mys_Goods_Tool/wiki/Installation#%E6%96%B9%E5%BC%8F%E4%BA%8C---%E9%80%9A%E8%BF%87-pypi-%E4%B8%8B%E8%BD%BD%E5%8C%85

**Comment by Zmincrix** [comment]
> 可以直接用系统的包管理器安装python和pip，然后用pip安装。

OK,搞定啦
