### ISSUE TITLE
大佬，请问stoken怎么获取？我用tool分析HAR文件什么都得不到，只能手动获取cookie，但是里面不包含stoken

### ISSUE THREAD

**Issue by hanserband** [Ljzd-PRO/Mys_Goods_Tool#17]

**Comment by hanserband** [comment]
获取用户actionticket失败

**Comment by Ljzd-PRO** [comment]
米游社App抓包开启后建议点一下兑换中心、账户设置之类的地方，获取到的信息会更多

**Comment by L6734250** [comment]
![IMG_20220621_202456](https://user-images.githubusercontent.com/102340873/174798524-40cad27f-87b2-4b9c-9061-79fccf5aecfc.png)
大佬，我手动填的，不行
![PZSZZU6UK~XPVC~I@{GBLS4(1)](https://user-images.githubusercontent.com/102340873/174798643-1a9299be-3f6d-43ba-a0a7-ddf4a4906f06.png)
