### ISSUE TITLE
linux上运行main 出现错误

### ISSUE THREAD

**Issue by Jinyihua** [Ljzd-PRO/Mys_Goods_Tool#18]
File "main", line 1
SyntaxError: Non-UTF-8 code starting with '\xaf' in file main on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by Ljzd-PRO** [comment]
似乎和代码编码有关，修改了一下 https://github.com/Ljzd-PRO/Mys_Goods_Tool/commit/ed466877949bcdfab36a869b90622342ec6b0ec1 https://github.com/Ljzd-PRO/Mys_Goods_Tool/commit/cc7a692499627cc0ece19445327657ab929a18e2
GitHub Action会自动编译，可以试试修改后的：https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/2442734951

**Comment by Jinyihua** [comment]
似乎是python3 来运行
Python2.7运行会
![image](https://user-images.githubusercontent.com/19164606/172047436-5c43e640-69ea-4c42-918c-23d732f3be41.png)

python3运行需要补齐request库 ntplib库 ping库 
目前运行没问题了感谢感谢
