### ISSUE TITLE
大佬配置好了发现用不了，tools和main好像都有点问题😂

### ISSUE THREAD

**Issue by just6a6name** [Ljzd-PRO/Mys_Goods_Tool#19]
![image](https://user-images.githubusercontent.com/51042346/172615500-bbc53438-4ed4-4325-bd37-cd1a40ec88ac.png)
![image](https://user-images.githubusercontent.com/51042346/172615524-afdec910-2966-48f0-a52e-73b7ba5675e5.png)
![image](https://user-images.githubusercontent.com/51042346/172616527-8846e497-5c47-4f81-82c8-947701e9696e.png)
**ck和各种参数都抓了照着格式填的，之前以为格式错了特地重新试了下发现还是不行😥**

**想用工具自动获取，但是黄鸟导出的json分析不了？看了下文件里里面是有所有数据的😂**
![image](https://user-images.githubusercontent.com/51042346/172617895-459cdfec-ce0d-4bb9-8fca-469f23779167.png)

**Comment by Ljzd-PRO** [comment]
> **想用工具自动获取，但是黄鸟导出的json分析不了？看了下文件里里面是有所有数据的😂** 

对，目前只能分析.har文件

**Comment by Ljzd-PRO** [comment]
另外如果后台开了网络代理相关的软件也要关闭

**Comment by just6a6name** [comment]
> 试一下获取`tool.exe`获取商品ID信息的功能能不能正常使用，这个功能是不需要配置Cookie的

确实，关了v2之后就可以查到id了
![image](https://user-images.githubusercontent.com/51042346/172756140-a5e0aaef-8200-458f-bbbc-43f97a8258ee.png)
![image](https://user-images.githubusercontent.com/51042346/172756215-2ed0a8bf-c442-420f-a682-ff89e3412ccb.png)
看来是v2的问题，因为配置了规则挂习惯了，就没有注意，谢谢大佬😘

**Comment by Ljzd-PRO** [comment]
> **顺便问一下 ，国内🐓放linux自动同步时间是不是会会比win版更好用？ 算了直接全都一起挂😂**

应该是都差不多的
