### ISSUE TITLE
cookie获取

### ISSUE THREAD

**Issue by 1941260986** [Ljzd-PRO/Mys_Goods_Tool#2]
用户cookie是通过抓米游社app的包获取 还是在pc上访问bbs.mihoyo.com/ys获取。

**Comment by Ljzd-PRO** [comment]
我是抓取米游社App的数据获取的。例如抓取点赞这个动作的POST数据，能找到`stuid`和`stoken`

**Comment by Ljzd-PRO** [comment]
网页版的话，如果能抓取到那两个数据应该也可以

**Comment by Ljzd-PRO** [comment]
我是先手动在App进行兑换，并抓包下来，从而获取cookies。
有时间我再看看cookies里只需要填什么数据，看看能不能有更简单抓取的方式。

**Comment by Ljzd-PRO** [comment]
抓包到的cookies包含形如
```
"account_id=...; cookie_token=...; ltoken=...; ltuid=...; login_ticket=...; aliyungf_tc=...; _ga_KJ6J9V9VZQ=...; _ga=...; _MHYUUID=...; UM_distinctid=...; _ga_6ZB57V7XXT=...; mi18nLang=...; _ga_831VBKXN1V=...; _ga_CXN1FSHKS4=...; _ga_9TTX3TE5YL=..." 
```
的数据即可，可以看 [config.ini](https://github.com/Ljzd-PRO/Mys_Goods_Tool/blob/main/config.ini) 的参考示例。
访问米游社App的 兑换中心 页面时，其中有很多GET请求的请求头中cookies就包含这些信息。
例如：
![35661400-97CA-4200-AFB4-F59122C9E029](https://user-images.githubusercontent.com/63289359/155575857-03032ef3-9157-4508-8474-66a8b94adf9a.jpeg)

**Comment by Ljzd-PRO** [comment]
好的
