### ISSUE TITLE
大佬，抓包软件一开米游社就失联咋回事

### ISSUE THREAD

**Issue by L6734250** [Ljzd-PRO/Mys_Goods_Tool#21]
用的packet capture，，HttpCanary是不是小蓝鸟，用着也失联

**Comment by Ljzd-PRO** [comment]
> 用的packet capture，，HttpCanary是不是小蓝鸟，用着也失联

HttpCanary应该是小黄鸟。
App内无法联网，可能是因为抓包App的CA证书未作为系统证书被信任，安卓7.0开始大多App只信任系统证书，而不是用户自己添加的用户证书，需要ROOT来把证书移到系统信任证书目录，或者反编译并修改App的配置文件，不过我改过以后，米游社就闪退了，可能是有完整性检查。
如果无法ROOT，比较方便的就是用安卓模拟器或者安卓端VMOS虚拟机

**Comment by Ljzd-PRO** [comment]
#14 可以参考一下

**Comment by sola97** [comment]
可以安卓7.0的模拟器+adb替换系统证书
教程：https://gist.github.com/pwlin/8a0d01e6428b7a96e2eb?permalink_comment_id=3969195#gistcomment-3969195

**Comment by L6734250** [comment]
> > 用的抓包，，HttpCanary不是小蓝鸟，用着也失联
> 
> HttpCanary应该是小鸟。 App无法内部联网，可能是因为抓包的CA证书未作为系统证书被信任，安卓7.0开始大部分App只信任自己的系统证书，而不是用户的用户证书，需要ROOT来添加证书移动系统信任了目录，但是我改过以后安装并修改应用程序的文件，但我过去改过，米游社就可以，可能是 RO 有故障检测，或者不能正常使用 。器或者安卓端VMOS虚拟机



> > 用的抓包，，HttpCanary不是小蓝鸟，用着也失联
> 
> HttpCanary应该是小鸟。 App无法内部联网，可能是因为抓包的CA证书未作为系统证书被信任，安卓7.0开始大部分App只信任自己的系统证书，而不是用户的用户证书，需要ROOT来添加证书移动系统信任了目录，但是我改过以后安装并修改应用程序的文件，但我过去改过，米游社就可以，可能是 RO 有故障检测，或者不能正常使用 。器或者安卓端VMOS虚拟机

![Screenshot_2022-06-21-19-47-41-762_com android fileexplorer](https://user-images.githubusercontent.com/102340873/174792885-2f844f10-b96d-4ccc-97e3-b6b74d9ce3df.jpg)
大佬，小黄鸟怎么把抓包数据转为har格式啊

**Comment by L6734250** [comment]
我导出来是这个格式

**Comment by L6734250** [comment]
![IMG_20220621_202456](https://user-images.githubusercontent.com/102340873/174798794-f47827b9-e614-4a04-8ad2-567bca537ade.png)
![PZSZZU6UK~XPVC~I@{GBLS4(1)](https://user-images.githubusercontent.com/102340873/174798803-988a7f6e-291c-442e-89e2-25f48008d2ae.png)
大佬，我手动填的不行

**Comment by L6734250** [comment]
查询送货地址Adress_iID那个

**Comment by L6734250** [comment]
大佬，我手动填的，检查了几遍感觉没错
![4_ZAB%$29(G9Y8XHR4)E0GG(1)](https://user-images.githubusercontent.com/102340873/174804786-f670a9bf-c2a6-498e-832a-92d20d224932.png)
![WBQW76_GYCV4V DTF~GF1MW(1)](https://user-images.githubusercontent.com/102340873/174804798-99c12fa2-519d-4c3b-93e6-093a22f076f3.png)
![Uploading P3EIIS3CM[}[2_}7JP_AF]G.png…]()

**Comment by L6734250** [comment]
所以小黄鸟的抓包数据怎么转为har格式啊(๑°⌓°๑)

**Comment by Ljzd-PRO** [comment]
> 大佬，我手动填的，感觉没错，还是读取失败

应该是编码问题，可以先下载最新改过的：https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/2495138726
之后会再发布新的发行版。

**Comment by Ljzd-PRO** [comment]
> 所以小黄鸟的抓包数据怎么转为har格式啊(๑°⌓°๑)

好像目前还没有工具可以转换，只能自己找了，需要的信息都在域名为`api-takumi.mihoyo.com`的请求里。
之后我再加上对小黄鸟文件的支持。

**Comment by L6734250** [comment]
> 

感谢大佬
