### ISSUE TITLE
网页端获取的cookie无法使用

### ISSUE THREAD

**Issue by magic5al** [Ljzd-PRO/Mys_Goods_Tool#23]
首先感谢佬，我已经用手机抓包操作成功过。
但我想图个方便，用网页端获取，方法是从别的地方学的，如下
![2ade0cde9d4adc2d](https://user-images.githubusercontent.com/91271243/174472526-d70decbd-d8c3-4ad2-bb91-582c1a15cb3b.png)
（使用插件cookie editor更方便）
能够获取到所有需要的字符串
填好后能获取商品信息和地址
但运行main.exe会显示

2022-06-19 10:39:56  ERROR  获取用户ActionTicket失败，正在重试  
2022-06-19 10:39:56  INFO  正在获取用户ActionTicket

比较好奇这是为什么

再一次感谢佬

**Comment by magic5al** [comment]
http://bbs.mihoyo.com/ys/

http://user.mihoyo.com/

var cookie=document.cookie;var ask=confirm('Cookie:'+cookie+'\n\nDo you want to copy the cookie to the clipboard?');if(ask==true){copy(cookie);msg=cookie}else{msg='Cancel'}

**Comment by Ljzd-PRO** [comment]
> 2022-06-19 10:39:56 ERROR 获取用户ActionTicket失败，正在重试 2022-06-19

网页端获取的Cookie可能缺少`stoken`，要兑换游戏内物品的话，需要用户的游戏账号信息，获取游戏服务器区号，而获取账号信息就需要`ActionTicket`，获取`ActionTicket`需要`stoken`

**Comment by magic5al** [comment]
> 

哦哦哦确实是少了stoken，我以为stoken不在引号里就是可不填，谢谢解答（不过，config.ini里面写的是“stoken可选，如果需要兑换游戏内物品则需要填写”，所以这句话是不是应该改一下？这么说来我之前用手机抓包也是报这个错，没填stoken）

**Comment by magic5al** [comment]
我确认了一下，我兑换的并不是游戏内物品

**Comment by Ljzd-PRO** [comment]
写在`Cookie`的字符串里或者单独写在下面的`stoken`里都可以，另外`stoken`项不需要加上引号。如果兑换的不是游戏内物品，`stoken`可以留空，但是目前必须要有这一项才行，不然会报错，后面这方面会改进。
v1.2.0之前的版本可能有Bug，会导致即使兑换的不是游戏内物品，也必须填写`stoken`

**Comment by magic5al** [comment]
哦哦，确实，我用的版本是老版本，谢谢佬的耐心解答~

**Comment by magic5al** [comment]
我刚刚遇到了一个问题，使用同样的配置文件，老版的可以正常获得送货地址，新版会显示“读取cookie失败，请手动输入cookie信息：（返回上一页请直接回车）”。这时候我再把配置文件里的cookie再粘贴一遍到对话框才能获得送货地址，有点怪

**Comment by Ljzd-PRO** [comment]
可能是因为新版本去掉了使用UTF-8编码读取配置文件的选项，不过目前已经重新再加上了。 #22 
在这里可以下载自动打包的exe：https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/2495138726

**Comment by magic5al** [comment]
嗯嗯，可以了，谢谢~
