### ISSUE TITLE
获取stoken

### ISSUE THREAD

**Issue by arukasxy** [Ljzd-PRO/Mys_Goods_Tool#32]
怎么手动获取stoken 或者怎么使用tool.exe,如果使用firefox登录米游社网页，然后在开发者模式的网络中右键“所有内容另存为HAR”后得到的HAR文件，tool.exe会显示 文件错误或损坏，要求 .har 文件(回车以返回)

**Comment by Ljzd-PRO** [comment]
寻找域名为 `api-takumi.mihoyo.com` 的请求，在Header的Cookie处查找，一般`stuid`和`stoken`是在一起的。

**Comment by imythu** [comment]
> 寻找域名为 `api-takumi.mihoyo.com` 的请求，在Header的Cookie处查找，一般`stuid`和`stoken`是在一起的。

请问下，这个域名的cookie也没有这个stoken咋办啊

**Comment by Ljzd-PRO** [comment]
#23 
应该是网页端Cookies不包含stoken，需要App

**Comment by imythu** [comment]
> #23 应该是网页端Cookies不包含stoken，需要App

那我手机抓个包试试，感谢😄

**Comment by imythu** [comment]
> #23 应该是网页端Cookies不包含stoken，需要App

请问下米游社APP咋抓包的啊，APP好像设置了只信任指定证书，抓不了😂

**Comment by arukasxy** [comment]
> > [#23 ](https://github.com/Ljzd-PRO/Mys_Goods_Tool/issues/23) 应该是网页端Cookies不包含stoken，需要App
> 
> 请问下米游社APP咋抓包的啊，APP好像设置了只信任指定证书，抓不了 😂

可以在mumu模拟器中抓包

**Comment by imythu** [comment]
> 

有相关的教程地址吗？

**Comment by Ljzd-PRO** [comment]
> 有相关的教程地址吗？

用HttpCanary。导出域名为 `api-takumi.mihoyo.com` 的请求，会导出一个文件夹，`tool` 工具可以分析出Cookie信息

**Comment by Ljzd-PRO** [comment]
直接在HttpCanary里搜索也可以

**Comment by imythu** [comment]
> 直接在HttpCanary里搜索也可以

这个安装不了证书，算了，不弄这个了，谢谢啦

**Comment by mhy289** [comment]
要导出har类型文件吗？我用httpcananry导出hcy类型文件，怎么办

**Comment by Ljzd-PRO** [comment]
> 要导出har类型文件吗？我用httpcananry导出hcy类型文件，怎么办

新版本可以使用HttpCanary导出的文件夹。建议HttpCanary导出时选择压缩，转移文件以后在解压，因为每个请求都会有很多文件，加起来有非常多的小文件。

**Comment by mhy289** [comment]
哪个版本的HttpCanary，我没有这个功能

> > 要导出har类型文件吗？我用httpcananry导出hcy类型文件，怎么办
> 
> 新版本可以使用HttpCanary导出的文件夹。建议HttpCanary导出时选择压缩，转移文件以后在解压，因为每个请求都会有很多文件，加起来有非常多的小文件。

**Comment by Ljzd-PRO** [comment]
> 哪个版本的HttpCanary，我没有这个功能
> 
> > > 要导出har类型文件吗？我用httpcananry导出hcy类型文件，怎么办
> > 
> > 
> > 新版本可以使用HttpCanary导出的文件夹。建议HttpCanary导出时选择压缩，转移文件以后在解压，因为每个请求都会有很多文件，加起来有非常多的小文件。

没有压缩选项的话就手动压缩吧，转移过去以后解压，tool 工具选择导出的那个文件夹的路径
