### ISSUE TITLE
读取配置文件失败

### ISSUE THREAD

**Issue by arukasxy** [Ljzd-PRO/Mys_Goods_Tool#33]
2022-06-28 16:53:52  INFO  正在校对互联网时间
2022-06-28 16:53:41  ERROR  读取配置文件失败
2022-06-28 16:53:41  ERROR  Traceback (most recent call last):
  File "main.py", line 131, in <module>
  File "configparser.py", line 698, in read
  File "configparser.py", line 1086, in _read
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'E:\\miyousheduihuan\\config.ini', line: 1
'\ufeff[Config]\n'

**Comment by Ljzd-PRO** [comment]
> 2022-06-28 16:53:52 INFO 正在校对互联网时间
> 2022-06-28 16:53:41 ERROR 读取配置文件失败
> 2022-06-28 16:53:41 ERROR Traceback (most recent call last):
> File "main.py", line 131, in 
> File "configparser.py", line 698, in read
> File "configparser.py", line 1086, in _read
> configparser.MissingSectionHeaderError: File contains no section headers.
> file: 'E:\miyousheduihuan\config.ini', line: 1
> '\ufeff[Config]\n'

把读取编码改成了`utf-8-sig`，可以先试试：https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/2575711056
可能要过一会运行完了才能下载
