### ISSUE TITLE
获取用户ActionTicket失败

### ISSUE THREAD

**Issue by arukasxy** [Ljzd-PRO/Mys_Goods_Tool#34]
2022-06-28 20:09:16  INFO  正在获取用户ActionTicket
2022-06-28 20:09:16  ERROR  获取用户ActionTicket失败，正在重试(3)
2022-06-28 20:09:16  ERROR  Traceback (most recent call last):
  File "main.py", line 329, in __init__
TypeError: 'NoneType' object is not subscriptable

**Comment by Ljzd-PRO** [comment]
一种可能是，如果米游社App账号登出了，原来的stoken会失效

**Comment by arukasxy** [comment]
![图片](https://user-images.githubusercontent.com/45310644/176239486-bb26c54f-41e0-443d-b0e7-4e3961771f56.png)
信息里有登录失效，但是stoken再抓包并没有变化，不过是在模拟器上获取的stoken，在网页上获取的login_ticket等其他信息

**Comment by Ljzd-PRO** [comment]
所有Cookie统一使用App端的试试

**Comment by arukasxy** [comment]
App端米游社用HttpCanary抓到的不知道怎么导出，手动看的话里面只有stuid、mid和stoken,没有其他信息
![图片](https://user-images.githubusercontent.com/45310644/176337005-28af3354-c457-48df-9511-6a7b25a0bff3.png)

**Comment by Ljzd-PRO** [comment]
> App端米游社用HttpCanary抓到的不知道怎么导出，手动看的话里面只有stuid、mid和stoken,没有其他信息
> ![图片](https://user-images.githubusercontent.com/45310644/176337005-28af3354-c457-48df-9511-6a7b25a0bff3.png)

在其他的请求里会有别的Cookie信息。通常`stuid`、`stoken`不会和它们在一起。
导出的话，在请求列表中右上角选择全选，然后长按任意一条请求，可以找到导出或保存，可以选择压缩，方便移动（因为里面包含数量很多的小文件），之后再解压

**Comment by arukasxy** [comment]
改成了同一个App抓取的信息，但是还是传回来“登录失效，请重新登录”

**Comment by Ljzd-PRO** [comment]
截图一下config.ini，部分打码，确认一下

**Comment by arukasxy** [comment]
![图片](https://user-images.githubusercontent.com/45310644/176488500-37cfc7c5-d1fa-4e1a-a3ce-3f161cf2e7c3.png)
![图片](https://user-images.githubusercontent.com/45310644/176488620-a1ada3db-da64-4be6-9aab-7f405541b5ce.png)
![图片](https://user-images.githubusercontent.com/45310644/176488761-4344f136-7b36-4ba9-998e-620017397895.png)
![图片](https://user-images.githubusercontent.com/45310644/176489028-ce491204-90a6-4f17-8ed0-c58721dc5e7c.png)
现在显示玩获取ActionTicket失败后能跳出倒计时了

**Comment by Ljzd-PRO** [comment]
可以检查一下日志里DEBUG `getActionTicket_headers`，里面包含Cookie最终发送出去的样子，可以看看是否有问题

**Comment by Ljzd-PRO** [comment]
新版本 v1.3.0 增加了查找Cookies中的`mid`，现在需要`mid`才能获取ActionTicket，不然服务器就会返回登录失效。
https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/latest
