### ISSUE TITLE
cookie 中的 stoken 重复

### ISSUE THREAD

**Issue by OOKAMISAMA** [Ljzd-PRO/Mys_Goods_Tool#37]
这里是不是应该  cookie.find("stoken") == -1 ，找不到的时候才往 cookie 拼 stoken，现在拼出来的 cookie 会有两个 stoken

https://github.com/Ljzd-PRO/Mys_Goods_Tool/blob/56b5ef2eac3596f67f2d6c0e84ba3108d8207804/main.py#L180-L181

**Comment by Ljzd-PRO** [comment]
确实是这样的
