### ISSUE TITLE
填写了stoken还是提示未配置

### ISSUE THREAD

**Issue by Fnvelope** [Ljzd-PRO/Mys_Goods_Tool#39]
2022-07-13 15:02:20  ERROR  商品：2022071212819 为游戏内物品，由于未配置 stoken，放弃兑换该商品
请问stoken怎么获取
更新版本之后错误变成获取用户ActionTicket失败

**Comment by Ljzd-PRO** [comment]
stoken需要抓包App获取，米游社网页版的Cookies里是没有stoken的。

**Comment by Ljzd-PRO** [comment]
兑换游戏内物品需要获取游戏区号等信息，获取这些信息需要ActionTicket，获取ActionTicket需要stoken，所以出错了。

**Comment by Ljzd-PRO** [comment]
填写了还是无法获取ActionTicket的话，Cookies中还需要添加`mid`这个信息，现在还需要有`mid`才能获取ActionTicket
刚刚修改过的版本的 `tool` 工具现在可以查找到`mid`了: https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/2668012332

**Comment by Fnvelope** [comment]
> 填写了还是无法获取ActionTicket的话，Cookies中还需要添加`mid`这个信息，现在还需要有`mid`才能获取ActionTicket 刚刚修改过的版本的 `tool` 工具现在可以查找到`mid`了: https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/2668012332

mid是填到stoken项内，还是cookie里


加上mid之后显示登录成功了，等下次兑换试一试

**Comment by Ljzd-PRO** [comment]
> mid是填到stoken项内，还是cookie里

写在Cookie里
