### ISSUE TITLE
tool.py 工具自动获取cookie处理har文件编码有误

### ISSUE THREAD

**Issue by Everything0519** [Ljzd-PRO/Mys_Goods_Tool#42]
我从stream抓包下来后用tool.py自动处理获取cookie，遇到了unicodedecodeerror，实测用utf-8模式打开har文件即可
即第345行应该为
file_data = json.load(open(file_path, "r", encoding="utf-8"))
不然会认为文件损坏

此外除了mid数据 其余大多数数据都可以在网页版抓包获得
bbs.mihoyo.com
user.mihoyo.com
这两个网页中能抓到除mid和stoken外所有字段

stoken数据段可以访问
https://api-takumi.mihoyo.com/auth/api/getMultiTokenByLoginTicket?login_ticket={}&token_types=3&uid={}获得
其中uid字段为网页端可获取的stuid数据段

另外 本人抓取了大量米游社内容 但是就是没有找到mid... 不知道是不是因为系统更改了之类的.. 望解答

**Comment by Ljzd-PRO** [comment]
好的，了解了。网页版的话，我再多看看

**Comment by Ljzd-PRO** [comment]
如果网页端的stoken不是`v2__ … ==`，`v2__` 开头 `==` 结尾 这样的形式的话，应该是不需要mid的。

**Comment by Everything0519** [comment]
> 如果网页端的stoken不是`v2__ … ==`，`v2__` 开头 `==` 结尾 这样的形式的话，应该是不需要mid的。

**Comment by Everything0519** [comment]
> > 如果网页端的stoken不是`v2__ … ==`，`v2__` 开头 `==` 结尾 这样的形式的话，应该是不需要mid的。

好的，请问就是显示了离开始还有多久多久就是成功运行了是吧

**Comment by Ljzd-PRO** [comment]
> 好的，请问就是显示了离开始还有多久多久就是成功运行了是吧

最好是临时改一下兑换时间，进行一下测试，如果能返回未到兑换时间或者库存不足之类的就说明可以了

**Comment by Everything0519** [comment]
昨天成功抢到了鼠标垫，谢谢大佬 但是我除了鼠标垫 还设置了原石的兑换 但是返回结果却是商品初始化失败 能都请教下是什么原因呢

**Comment by Everything0519** [comment]
谢谢，研究了一下日志是因为没有mid.. 以为您之前的描述的意思是不需要mid这个cookie就能运行 看了下你新发布的1.4版本已经不需要mid这个cookie了 打算试试看 谢谢谢谢

**Comment by Ljzd-PRO** [comment]
> 谢谢，研究了一下日志是因为没有mid.. 以为您之前的描述的意思是不需要mid这个cookie就能运行 看了下你新发布的1.4版本已经不需要mid这个cookie了 打算试试看 谢谢谢谢

`stoken` 为 "v2"类型(开头为`v2__`末尾为`==`)的情况下需要有 `mid`，新版本米游社App就是这种stoken，但网页版还是以前那种，不需要mid。
新版本发布了，可以在里面直接登录，这样也不需要浏览器开发者模式和抓包之类的了：https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v1.4.0
