### ISSUE TITLE
主程序运行完成后窗口未保持

### ISSUE THREAD

**Issue by pxxchhh** [Ljzd-PRO/Mys_Goods_Tool#47]
1.3与1.4版本，在配置完cookies等信息之后，尝试设置一个虚假时间（因为看到作者大大说可以配置完后可以设置时间来测试是否返回未到兑换时间），运行主程序，到指定时间完成任务后就自动关闭窗口，来不及看到其返回信息

**Comment by Ljzd-PRO** [comment]
可以查看日志文件，或在程序所在文件夹下按住`Shift`然后右键，打开终端，在终端里输入`./main.exe`，这样运行结束以后窗口不会立刻关闭
