### ISSUE TITLE
timeUp在isCheck为False时未定义

### ISSUE THREAD

**Issue by qutong20** [Ljzd-PRO/Mys_Goods_Tool#49]
`timeUp`在`if isCheck`内定义：
https://github.com/Ljzd-PRO/Mys_Goods_Tool/blob/c4d13863ab877a172326e20bad86d0d1c8d4a317/main.py#L545-L551
因此，在`isCheck` 为`False`时，
https://github.com/Ljzd-PRO/Mys_Goods_Tool/blob/c4d13863ab877a172326e20bad86d0d1c8d4a317/main.py#L621
使用`timeUp`时会出现错误。

### 可能的解决方案
可以考虑在该行之后定义`timeUp`。
https://github.com/Ljzd-PRO/Mys_Goods_Tool/blob/c4d13863ab877a172326e20bad86d0d1c8d4a317/main.py#L523

**Comment by Ljzd-PRO** [comment]
了解了
