### ISSUE TITLE
用fiddler进行手机抓包 米游社抓不了 会提示没有网络 那是要用什么抓包？

### ISSUE THREAD

**Issue by cxs-fight** [Ljzd-PRO/Mys_Goods_Tool#5]

**Comment by Ljzd-PRO** [comment]
米游社没有限制抓包，大多请求都没有加密。
Fiddler的话我没有用过，不过如果说抓包显示无网络的话，很多时候是没有配置好HTTPS证书，没有信任抓包工具的证书。
我是手动兑换之前开启抓包，点击兑换以后再查看发出的数据的。

**Comment by cxs-fight** [comment]
https证书一直都有配 但还是不行 估计得像另一个issue里那位老哥一样把手机root了

**Comment by Ljzd-PRO** [comment]
今天我也用安卓抓包了一下，似乎是由于安卓11和12的限制，需要root才能将证书添加到系统CA列表。否则要用VOMS这样的虚拟机，HttpCanary还可以安装平行空间，也是为非root设备提供的方案。
