### ISSUE TITLE
next_time和sale_start_time不一致

### ISSUE THREAD

**Issue by lhllhx** [Ljzd-PRO/Mys_Goods_Tool#51]
https://api-takumi.mihoyo.com/mall/v1/web/goods/detail?app_id=1&point_sn=myb&goods_id=2022081014864

如链接所示 应该以sale_start_time为准

**Comment by Ljzd-PRO** [comment]
了解了

**Comment by lhllhx** [comment]
有空的话建议部分重构一下 获取确定兑换时间直接在main.py完成即可 （临时方案tool里面改也行）

**Comment by Ljzd-PRO** [comment]
`sale_start_time`好像不准，ID 2022071212721【原神】大英雄的经验*5，兑换时间得到的是`2022-08-10 19:00:00`，实际上App里看到的是`2022-08-17 19:00:00`

**Comment by lhllhx** [comment]
mhy这api真是让人迷惑 我复现不出来了 当时我换[2022081014864](https://api-takumi.mihoyo.com/mall/v1/web/goods/detail?app_id=1&point_sn=myb&goods_id=2022081014864)时还是sale_start_time是对的 next_time是错的  
当时（8月10）sale_start_time为8月11 next_time为8月18 app显示是8月11 且bbs里面的商品都是sale_start_time为准
现在我看全是以next_time为准

**Comment by lhllhx** [comment]
存个档吧 真是让人迷惑
{"retcode":0,"message":"OK","data":{"app_id":1,"goods_id":"2022081014864","goods_name":"【米游社】美的(Midea)小夜灯  暮光（普通机械款）","goods_desc":"","goods_detail":"\u003cp\u003e\u003cstrong\u003e商品描述\u003c/strong\u003e：美的(Midea)小夜灯 \u0026nbsp;暮光（普通机械款）\u003c/p\u003e\n\n\u003cp\u003e\u003cstrong\u003e商品毛重\u003c/strong\u003e：50.00g\u003c/p\u003e\n\n\u003cp\u003e\u003cstrong\u003e色温\u003c/strong\u003e：暖光（3300K以下）\u003c/p\u003e\n\n\u003cp\u003e\u003cstrong\u003e光源固定方式\u003c/strong\u003e：插座\u003c/p\u003e\n\n\u003cp\u003e\u003cstrong\u003e兑换次数\u003c/strong\u003e：每位用户仅可兑换一次哦~数量有限，兑完即止\u003c/p\u003e\n\n\u003cp\u003e\u003cstrong\u003e发货情况\u003c/strong\u003e：我们会在60个工作日内安排发货【米游姬徒手拣货，望小伙伴海涵】\u003c/p\u003e\n","icon":"https://webstatic.mihoyo.com/upload/shop/2022/07/13/f35ccfb73b8a7a899818872e7aac33dc_6434611922710739839.jpg","type":4,"price":3500,"cover":[{"type":"","url":"https://webstatic.mihoyo.com/upload/shop/2022/07/13/f35ccfb73b8a7a899818872e7aac33dc_6434611922710739839.jpg"}],"point_sn":"myb","unlimit":false,"total":0,"account_cycle_type":"forever","account_cycle_limit":1,"account_exchange_num":0,"role_cycle_type":"not_limit","role_cycle_limit":0,"role_exchange_num":0,"rules":[{"rule_id":1,"values":["5:4"]}],"game":"bbs","game_biz":"bbs_cn","start":"1659283200","end":"1661961600","status":"online","bbs_detail":[],"next_time":1660795200,"sale_start_time":"1660190400","next_num":40,"now_time":1660730476}}

{"retcode":0,"message":"OK","data":{"app_id":1,"goods_id":"2022071212721","goods_name":"【原神】大英雄的经验*5","goods_desc":"","goods_detail":"\u003cp\u003e\u003cstrong\u003e商品描述\u003c/strong\u003e：大英雄的经验*5\u003cstrong\u003e（2.8版本特供！）\u003c/strong\u003e\u003c/p\u003e\n\n\u003cp line=\"WmSI\"\u003e\u003cstrong\u003e兑换限制\u003c/strong\u003e：米游社 - 原神频道等级达到3级；原神游戏冒险等阶达到20级\u003c/p\u003e\n\n\u003cp line=\"z8EX\"\u003e\u003cstrong\u003e兑换次数\u003c/strong\u003e：每位用户每个游戏版本仅可兑换一次哦~数量有限，兑完即止。\u003c/p\u003e\n\n\u003cp line=\"z8EX\"\u003e\u003cstrong\u003e物品领取\u003c/strong\u003e：兑换后会以游戏内邮件形式发放到绑定的角色账号，邮件有效期30天，请登录游戏查收（注意：邮件发放可能会有少许延迟，过期不领邮件会消失）\u003c/p\u003e\n","icon":"https://webstatic.mihoyo.com/upload/shop/2021/10/20/468097d8c7fb608f3a23d057d871e48a_7303233958715687443.png","type":2,"price":1500,"cover":[{"type":"","url":"https://webstatic.mihoyo.com/upload/shop/2021/10/20/468097d8c7fb608f3a23d057d871e48a_7303233958715687443.png"}],"point_sn":"myb","unlimit":false,"total":0,"account_cycle_type":"forever","account_cycle_limit":1,"account_exchange_num":0,"role_cycle_type":"not_limit","role_cycle_limit":0,"role_exchange_num":0,"rules":[{"rule_id":1,"values":["2:3"]},{"rule_id":2,"values":["20"]}],"game":"hk4e","game_biz":"hk4e_cn","start":"1657555200","end":"1661184000","status":"online","bbs_detail":[],"next_time":1660734000,"sale_start_time":"1660129200","next_num":4000,"now_time":1660730519}}

**Comment by Ljzd-PRO** [comment]
似乎是根据["data"]["status"]而定的，为`online`则是`next_time`，为`not_in_sale`则是`sale_start_time`
