### ISSUE TITLE
mac 10.14.6 运行tool报错

### ISSUE THREAD

**Issue by hww-github** [Ljzd-PRO/Mys_Goods_Tool#53]
报错如下图：
![image](https://user-images.githubusercontent.com/62824191/187114301-c8b1bb5a-b69d-440f-99f4-854383a5cd80.png)
是不支持10.14.6吗？能不能支持一下

**Comment by Ljzd-PRO** [comment]
看起来是剪切板模块最低10.15，我尝试加一下根据系统版本进行模块的导入

**Comment by Ljzd-PRO** [comment]
现在可以再试试：https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/2946377511

**Comment by hww-github** [comment]
> 现在可以再试试：https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/2946377511

工具可以运行了，但是打开的时候提示剪切板导入失败，提示如下图：
![image](https://user-images.githubusercontent.com/62824191/187332248-2b476001-4c05-4837-9762-e457f7775804.png)

**Comment by Ljzd-PRO** [comment]
因为程序是GitHub Actions的macOS 10.15服务器打包的，所以这个剪切板功能可能对10.14和以下不兼容了，所以这里会导入失败，不过问题也不大，只是不会自动复制网址到剪切板了，手动复制也一样。
