### ISSUE TITLE
缺少业务编号

### ISSUE THREAD

**Issue by xuxin666666** [Ljzd-PRO/Mys_Goods_Tool#55]
![image](https://user-images.githubusercontent.com/58601208/188318444-f91284b7-7bde-48ee-adf1-73fb6621fe5a.png)
想先试试水，就拿那个米游社7天头像框试了一下，结果不管是我自己抓参数，还是使用tool.py来抓，都返回的这个，这咋办呢

**Comment by Ljzd-PRO** [comment]
这类商品还没测试过。主要是用来兑换限时限量的商品，测试的话，时间没到也可以自己改兑换时间来测试，返回未到时间或者商品库存不足就说明没问题。

**Comment by xuxin666666** [comment]
抢到了，谢谢大佬
