### ISSUE TITLE
关于兑换游戏内物品补全cookie

### ISSUE THREAD

**Issue by CleverMod** [Ljzd-PRO/Mys_Goods_Tool#56]
请问新版本1.4.2想要兑换游戏内物品还需要补全cookie吗  我补全以后查询送货id就查询失败了

**Comment by Ljzd-PRO** [comment]
只有浏览器开发者模式下获取的Cookie需要补全

**Comment by CleverMod** [comment]
> 只有浏览器开发者模式下获取的Cookie需要补全
好的 谢谢
