### ISSUE TITLE
部分商品未被列出

### ISSUE THREAD

**Issue by klbcko** [Ljzd-PRO/Mys_Goods_Tool#57]
大佬，怎么程序查找商品ID里面有的商品没出现呀？

**Comment by Ljzd-PRO** [comment]
什么商品呢？

**Comment by klbcko** [comment]
![QQ图片20220928121612](https://user-images.githubusercontent.com/104831793/192686392-e59ac218-393e-4557-bd33-dfb88ca6ef14.jpg)这个是米游社今天开放兑换的
![image](https://user-images.githubusercontent.com/104831793/192686421-ca2558ea-9344-48e6-8076-9fb32c39b4bb.png)
![image](https://user-images.githubusercontent.com/104831793/192686523-dedeceef-6d75-4243-a0de-c22cd4eda29e.png)
程序里只有这几个，查不到我前面提到这些商品ID。

**Comment by Ljzd-PRO** [comment]
已售完的吗？

**Comment by klbcko** [comment]
> 已售完的吗？
这几个是在12：00开始兑换的，在12点之前，我用程序查看是没有显示的。
