### ISSUE TITLE
获取不到Address_ID

### ISSUE THREAD

**Issue by marivk** [Ljzd-PRO/Mys_Goods_Tool#58]
> 查询结果：

> 请输入你要选择的地址ID(Address_ID)：
-- 注意：将对 config.ini 配置文件进行写入，文件中的注释和排版将被重置
-- 按回车键跳过并返回功能选择界面
>

大佬能帮忙看看吗，win版本，address id查询结果是空的，log里也是空的，通过输入两次验证码登录配置的cookie

**Comment by Ljzd-PRO** [comment]
米游社账号设置里有添加收货地址吗？

**Comment by marivk** [comment]
谢谢大佬，原来是这里的收货地址
