### ISSUE TITLE
Adress_ID查询结果为空

### ISSUE THREAD

**Issue by Wind6666** [Ljzd-PRO/Mys_Goods_Tool#59]
Adress_ID查询结果为空怎么办？如果config文件不写Adress_ID影响游戏内虚拟物品的兑换吗？初次使用不太会用，希望大佬解答一下，谢谢！

**Comment by Ljzd-PRO** [comment]
为空的话说明没有添加地址，要去米游社App里先添加收货地址。在通行证设置里

**Comment by Ljzd-PRO** [comment]
>如果config文件不写Adress_ID影响游戏内虚拟物品的兑换吗？

应该会影响，但是不确定，因为兑换时发送的数据有地址ID这一项，没有设置地址ID的话，这一项的值就会是空的，要去掉地址ID这一项然后再发送请求，如果还是失败才能说明一定要地址ID。

**Comment by Ljzd-PRO** [comment]
#60 情况类似

**Comment by Wind6666** [comment]
> 为空的话说明没有添加地址，要去米游社App里先添加收货地址。在通行证设置里

我是邮箱注册的，刚刚发现手机号没注册通行证。那这个程序是只适用于手机账号吗？还是说我可以自己把cookie粘贴进config？config里的cookie格式和自己在网页获取的cookie格式一致吗？

**Comment by Ljzd-PRO** [comment]
> > 为空的话说明没有添加地址，要去米游社App里先添加收货地址。在通行证设置里
> 
> 我是邮箱注册的，刚刚发现手机号没注册通行证。那这个程序是只适用于手机账号吗？还是说我可以自己把cookie粘贴进config？config里的cookie格式和自己在网页获取的cookie格式一致吗？

可以自己获取Cookie然后复制粘贴进去，如果是在网页上用浏览器开发者模式获取的，那么要用 `tool` 工具里的补充Cookie补充一下，因为网页的Cookie缺少一项数据，要额外进行获取。

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/3234357242 可以下载刚刚修改后的版本了，兑换虚拟商品应该不需要地址ID了，可以随便设置一个兑换时间进行测试。
