### ISSUE TITLE
cookie怎么抓？

### ISSUE THREAD

**Issue by LOUTS4** [Ljzd-PRO/Mys_Goods_Tool#6]
_ga_KJ6J9V9VZQ=...; _ga=...; _MHYUUID=...; _ga_6ZB57V7XXT=...; mi18nLang=...; _ga_831VBKXN1V=...; _ga_CXN1FSHKS4=...; _ga_9TTX3TE5YL=...    就这些。。。没抓到过一次。。其他的都抓到了，就这些没有，大佬有法子吗

**Comment by Ljzd-PRO** [comment]
`Cookies`的示例里很多_ga开头的都意义不明，写出来主要是示例作用，大体上只要有`account_id=...; cookie_token=...; ltoken=...; ltuid=...; login_ticket=...;`这些信息即可，只要有这些信息，抓包到的整个Cookies就能填进去。
主要还是注释没写清楚。

**Comment by LOUTS4** [comment]
谢谢大佬

**Comment by LOUTS4** [comment]
大佬，那个请问一下米游社app的抓包数据文件如何获取

**Comment by LOUTS4** [comment]
大佬，我cookie明明是对的，但在tool里想获取送货地址，说读取cookie失败

**Comment by Ljzd-PRO** [comment]
> 大佬，那个请问一下米游社app的抓包数据文件如何获取

开启抓包软件，启动抓包，然后打开米游社App，再打开一下兑换中心页面，接着结束抓包，把api-takumi.mihoyou.com域名的网络请求全部勾选导出为har文件（也可以所有域名都导出，只是如果是用iOS Stream抓包的话，没有批量导出不方便）

**Comment by Ljzd-PRO** [comment]
> 大佬，我cookie明明是对的，但在tool里想获取送货地址，说读取cookie失败

可以看一下你的`config.ini`文件吗？Cookie和stoken的部分打码一下，主要看格式有没有出问题。

**Comment by LOUTS4** [comment]
大佬，稍等

**Comment by LOUTS4** [comment]
![5 1GYS@EQKB)BN9@PV(G9 X](https://user-images.githubusercontent.com/67259582/166098496-97cd8521-5db4-44a0-be43-6164c9f5d85b.png)

**Comment by LOUTS4** [comment]
![HC36O@XRDQ L_YW_BLCQEN7](https://user-images.githubusercontent.com/67259582/166098594-66d3e4b0-5813-41d9-9de9-db84ff0b6a71.png)

**Comment by Ljzd-PRO** [comment]
用管理员权限运行tool再试试

**Comment by LOUTS4** [comment]
好的

**Comment by LOUTS4** [comment]
还是不行

**Comment by LOUTS4** [comment]
算了，大佬，我自己再研究研究

**Comment by Ljzd-PRO** [comment]
你的电脑有Python环境吗，我刚刚增加了手动输入Cookies：https://github.com/Ljzd-PRO/Mys_Goods_Tool/commit/f0a274a67c24c1618450377269e7f942a40fb43f

**Comment by LOUTS4** [comment]
WC，大佬还没睡呢?辛苦大佬了

**Comment by Ljzd-PRO** [comment]
我通常比较晚睡😂

**Comment by LOUTS4** [comment]
那我先睡了，晚安大佬 ┗( ˘ω˘ )┛

**Comment by hanserband** [comment]
> 我通常比较晚睡😂

佬，
2022-05-22 09:30:50  ERROR  获取用户ActionTicket失败，正在重试  
2022-05-22 09:30:50  INFO  正在获取用户ActionTicket  
2022-05-22 09:30:50  ERROR  Traceback (most recent call last):
  File "main.py", line 192, in __init__
TypeError: 'NoneType' object is not subscriptable

这种错误怎么解决呀
