### ISSUE TITLE
{"data":null,"message":"缺少业务编号","retcode":-2005}

### ISSUE THREAD

**Issue by marivk** [Ljzd-PRO/Mys_Goods_Tool#60]
2022-10-12 19:08:41  INFO  兑换商品：2022092712366 返回结果：
{"data":null,"message":"缺少业务编号","retcode":-2005}

想试着兑换摩拉，一直返回缺少业务编号的错误，cookie适用tool抓的，大佬能帮忙看下吗

**Comment by marivk** [comment]
![image](https://user-images.githubusercontent.com/114583626/195330369-fc0f7ec4-bb5a-4819-bada-442b85987ae9.png)

**Comment by marivk** [comment]
![image](https://user-images.githubusercontent.com/114583626/195330572-5fa2f899-9c92-4a7f-98f7-381c52cbd20c.png)

**Comment by Ljzd-PRO** [comment]
和地址ID有关，可以先尝试设置了地址ID以后再兑换。
兑换虚拟商品不一定要地址ID，但程序没有适配这种情况，等会我改一下。

**Comment by Ljzd-PRO** [comment]
#59 也是相似的情况

**Comment by marivk** [comment]
#59的问题我之前遇到了然后设置了地址，并且也填进配置文件里了，图中的address_id的字段不是我的地址ID吗

**Comment by Ljzd-PRO** [comment]
等 https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/3234357242 打包好以后，就可以下载刚刚修改后的版本了

**Comment by marivk** [comment]
好的，谢谢大佬，我试下

**Comment by Ljzd-PRO** [comment]
> #59的问题我之前遇到了然后设置了地址，并且也填进配置文件里了，图中的address_id的字段不是我的地址ID吗

有设置游戏UID吗

**Comment by marivk** [comment]
有的，截图应该可以看到

**Comment by marivk** [comment]
试了最新的打包版本，问题依旧

2022-10-12 19:49:40  INFO  兑换商品：2022092712721 返回结果：
{"data":null,"message":"缺少业务编号","retcode":-2005}

**Comment by Ljzd-PRO** [comment]
会同时发送多个兑换请求，看一下米游社里是否实际上已经兑换成功

**Comment by marivk** [comment]
谢谢大佬，好像知道原因了，我把账号ID和UID搞混了
