### ISSUE TITLE
获取地址信息失败

### ISSUE THREAD

**Issue by CuteLittleSky** [Ljzd-PRO/Mys_Goods_Tool#61]
系统: Win Server2019
版本: 1.4.2
米游社中已确认添加收货地址(因为我之前手抢到过实物所以肯定有,又确认了一下)
已补全cookie

**Comment by Ljzd-PRO** [comment]
看一下日志信息，记得把隐私信息打码

**Comment by CuteLittleSky** [comment]
> 看一下日志信息，记得把隐私信息打码

tool.py没有日志信息生成

**Comment by CuteLittleSky** [comment]
已解决,自动补全Cookie问题,使用验证码获取Cookie就可以了
