### ISSUE TITLE
阿里云服务器间接性显示网络连接异常

### ISSUE THREAD

**Issue by mxyooR** [Ljzd-PRO/Mys_Goods_Tool#63]
![image](https://user-images.githubusercontent.com/88259089/201354430-cf9b38a3-6db2-4eec-b4cd-5455614bcfdd.png)
如图，windows自带的ping正常，但是python自带的ping3间接性返回0.0

**Comment by Ljzd-PRO** [comment]
如果有开了代理软件要关闭

**Comment by mxyooR** [comment]
没开代理

**Comment by Ljzd-PRO** [comment]
临时调一下兑换时间，可以测试一下兑换是否会有问题。

**Comment by mxyooR** [comment]
正常的兑换 谢谢！
