### ISSUE TITLE
关于cookie的mid&兑换结果502

### ISSUE THREAD

**Issue by lzh19999** [Ljzd-PRO/Mys_Goods_Tool#65]
用网页端短信验证码登陆获得了cookie，但是没看到参数mid，还有stoken在示例里没有，是需要手动添加吗?

**Comment by Ljzd-PRO** [comment]
不需要，只有网页开发者模式获取的Cookie需要补全。
mid也不是必须的，是否需要mid和stoken值有关，“v2”的stoken才需要mid，常见于手机App客户端

**Comment by lzh19999** [comment]
那请问502是什么错误，我今天试着抢了一下，报的502错误

**Comment by lzh19999** [comment]
我通过短信验证码获得的cookie是这种格式，请问有什么遗漏的吗，account_id=;cookie_token=;ltoken=;ltuid=;aliyungf_tc=;login_ticket=;stoken=;

**Comment by Ljzd-PRO** [comment]
> 那请问502是什么错误，我今天试着抢了一下，报的502错误

有完整的返回信息吗？

**Comment by Ljzd-PRO** [comment]
新版本经过测试可以正常运行：https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v1.4.3

**Comment by Kratosmax** [comment]
> 

我的还是依旧是2023-02-08 16:08:00  INFO  兑换商品：2023011612872 返回结果：
{"data":null,"message":"Something went wrong...please retry later","retcode":-502}

**Comment by Ljzd-PRO** [comment]
> 我的还是依旧是2023-02-08 16:08:00 INFO 兑换商品：2023011612872 返回结果：
> {"data":null,"message":"Something went wrong...please retry later","retcode":-502}

日志文件里有没有其他错误，例如和“uid”相关的

**Comment by Ljzd-PRO** [comment]
更改了UA和APP版本号的设置：https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v1.4.4
可能可以解决502的问题，下次兑换的时候我也试试

**Comment by Ljzd-PRO** [comment]
使用v2新版本：https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/latest
