### ISSUE TITLE
win7系统报错

### ISSUE THREAD

**Issue by 745243** [Ljzd-PRO/Mys_Goods_Tool#69]
用的租的机器，发现运行不了，运行就闪一下就没了，截了好几次终于截到了，大佬帮忙看一下，这个怎么解决
![$PFADMKJDNCCWU1$LNTE)EP](https://user-images.githubusercontent.com/103875402/206854460-19b6b306-db49-4c7c-b225-212e203fb461.png)

**Comment by Ljzd-PRO** [comment]
应该是因为Windows 7缺少一些依赖，exe是在Windows 10上打包的。
参考：https://stackoverflow.com/questions/56308454/loadlibrary-pyinstaller-format-messagew-failed
也可以尝试安装Python环境然后直接运行源码。

安装所需要的Python库可以在安装Python和PyPI后在项目目录下运行命令：
```
pip install -r requirements.txt
```
