### ISSUE TITLE
检测的时间由本地改为互联网时间

### ISSUE THREAD

**Issue by XTL676** [Ljzd-PRO/Mys_Goods_Tool#7]
米游社的60原石我之前手动抢了6次，一次都没抢到，今天终于抢到了，哈哈哈
非常感谢作者
[提一点小意见，检查时间可以改为检查网络时间，不用本地时间，因为可能有些设备的本地时间不准确，我这次就是在抢之前同步了一下时间]

**Comment by Ljzd-PRO** [comment]
好的。请问你是用[v1.2.0](https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v1.2.0)这个发行版还是[v1.2.0-beta.2](https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v1.2.0)，后者我测试了不能兑换游戏内物品，所以一两小时前更新了v1.2.0，那个是可以的

**Comment by XTL676** [comment]
用的v1.2.0-beta.2，当时连接游戏服务器时一直显示重试，我把main.py里的checkGame = "https://api-takumi.mihoyo.com/binding/api/getUserGameRolesByStoken"换成了checkGame = "https://api-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie"，即用cookie登录，就可以正常获取游戏角色的信息了

**Comment by Ljzd-PRO** [comment]
> 用的v1.2.0-beta.2，当时连接游戏服务器时一直显示重试，我把main.py里的checkGame = "[https://api-takumi.mihoyo.com/binding/api/getUserGameRolesByStoken"换成了checkGame](https://api-takumi.mihoyo.com/binding/api/getUserGameRolesByStoken%22%E6%8D%A2%E6%88%90%E4%BA%86checkGame) = "[https://api-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie"，即用cookie登录，就可以正常获取游戏角色的信息了](https://api-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie%22%EF%BC%8C%E5%8D%B3%E7%94%A8cookie%E7%99%BB%E5%BD%95%EF%BC%8C%E5%B0%B1%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E8%8E%B7%E5%8F%96%E6%B8%B8%E6%88%8F%E8%A7%92%E8%89%B2%E7%9A%84%E4%BF%A1%E6%81%AF%E4%BA%86)

好的
