### ISSUE TITLE
获取用户ActionTicket失败，放弃兑换该商品

### ISSUE THREAD

**Issue by Yoimiya-993** [Ljzd-PRO/Mys_Goods_Tool#72]
用tool.exe手机号加验证码获取的cookie
日志里报-100，还有获取ActionTicket失败
![image](https://user-images.githubusercontent.com/52495231/209941763-560ea2e1-9293-4f7e-8d7b-523853963218.png)
然后到19点兑换的时候的日志
![image](https://user-images.githubusercontent.com/52495231/209941819-4748353d-5ccf-4769-b7dd-e40610459186.png)
是什么原因，怎么解决？

**Comment by Ljzd-PRO** [comment]
可以试试看这个版本行不行：https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/3751278553
可以随便设定一个兑换时间，如果返回未到兑换时间之类的就没问题

**Comment by Ljzd-PRO** [comment]
新版本经过测试可以正常运行：https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v1.4.3

**Comment by Yoimiya-993** [comment]
好的，我试试

**Comment by Yoimiya-993** [comment]
![image](https://user-images.githubusercontent.com/52495231/210122875-a4f4b154-90f6-456a-967e-8f638347fd75.png)
这样就是正常了吧

**Comment by Ljzd-PRO** [comment]
> ![image](https://user-images.githubusercontent.com/52495231/210122875-a4f4b154-90f6-456a-967e-8f638347fd75.png)
> 这样就是正常了吧

对的
