### ISSUE TITLE
未初始化完成，放弃兑换

### ISSUE THREAD

**Issue by fleuranze** [Ljzd-PRO/Mys_Goods_Tool#76]
2023-02-16 12:00:00  WARN  鍟嗗搧锛?023020714763锛?023020714655 鏈垵濮嬪寲瀹屾垚锛屾斁寮冨厬鎹?
日志是乱码，main界面是“未初始化完成，放弃兑换”，是不能兑换多个吗？

**Comment by Ljzd-PRO** [comment]
还有别的日志信息吗

**Comment by fleuranze** [comment]
[mys_goods_tool.log](https://github.com/Ljzd-PRO/Mys_Goods_Tool/files/10773093/mys_goods_tool.log)

**Comment by fleuranze** [comment]
正常情况应该用文本编辑器就可以了。乱码应该是编码问题，不过之前还没有人遇到过乱码

**Comment by fleuranze** [comment]
请问正常情况下没有成功main界面会显示什么？我只成功过一次，其余都是未初始化完成，放弃兑换。两种方法都轮流试过，成功的一次是使用网页版补全cookie的方法，但是查询不到收货地址，验证码方法能查到但没兑换成功过。

**Comment by Ljzd-PRO** [comment]
没有成功的话会提示兑换失败，并且会显示服务器返回的信息

**Comment by RXUARJ** [comment]
2023-03-01 19:39:50  ERROR  检查游戏账户： 失败，正在重试(4)
2023-03-01 19:39:50  DEBUG  checkGame_url: https://api-takumi-record.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid=
2023-03-01 19:39:50  DEBUG  checkGame_response: {"data":null,"message":"Invalid uid","retcode":-1}
2023-03-01 19:39:50  ERROR  Traceback (most recent call last):
  File "/home/pi/Mys_Goods_Tool/main.py", line 367, in __init__
    user_list = res.json()["data"]["list"]
TypeError: 'NoneType' object is not subscriptable

**Comment by Ljzd-PRO** [comment]
应该还是程序的Bug，这里UID没有载入，是空的

**Comment by Ljzd-PRO** [comment]
用的是最新的v1.4.3吗

**Comment by RXUARJ** [comment]
对，1.4.3

**Comment by hhhggg233** [comment]
2023-03-02 15:19:41  INFO  正在检查游戏账户：100655013 的详细信息
2023-03-02 15:19:41  ERROR  检查游戏账户：100655013 失败，正在重试(1)
2023-03-02 15:19:41  DEBUG  checkGame_url: https://api-takumi-record.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid=77347599
2023-03-02 15:19:41  DEBUG  checkGame_response: {"data":null,"message":"Please login","retcode":10001}
2023-03-02 15:19:41  ERROR  Traceback (most recent call last):
  File "main.py", line 375, in __init__
TypeError: 'NoneType' object is not subscriptable
我的是这样，我手机号没法收验证码，用别的方法提取的cookie，用程序的补全cookie提示cookie是完整的

**Comment by fleuranze** [comment]
大佬，我大概知道为什么未初始化完成了，我没安装在C盘

**Comment by Ljzd-PRO** [comment]
> 大佬，我大概知道为什么未初始化完成了，我没安装在C盘

现在解决了吗？是 config.ini 文件和 main.exe、tool.exe 不在同一目录？需要在同一目录，并且可执行文件要在目录下运行的，就是说直接双击打开，或者如果在CMD终端通过命令来运行的话，需要在程序目录下执行命令。

**Comment by Ljzd-PRO** [comment]
> 2023-03-02 15:19:41 INFO 正在检查游戏账户：100655013 的详细信息
> 2023-03-02 15:19:41 ERROR 检查游戏账户：100655013 失败，正在重试(1)
> 2023-03-02 15:19:41 DEBUG checkGame_url: https://api-takumi-record.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid=77347599
> 2023-03-02 15:19:41 DEBUG checkGame_response: {"data":null,"message":"Please login","retcode":10001}
> 2023-03-02 15:19:41 ERROR Traceback (most recent call last):
> File "main.py", line 375, in **init**
> TypeError: 'NoneType' object is not subscriptable
> 我的是这样，我手机号没法收验证码，用别的方法提取的cookie，用程序的补全cookie提示cookie是完整的

是用什么方法获取的Cookie，手机App抓包吗？

**Comment by fleuranze** [comment]
> > 大佬，我大明白为什么未开始化完成了，我没安装在C盘
> 
> 现在解决了吗？是config.ini文件和main.exe、tool.exe不在同一个目录？要在同一个目录，而可执行文件要在目录下运行的，就是说直接访问双点击打开CM，或者在CM命令来运行的话语，需要在程序目录下执行命令。

我不是这个意思，应该这样说，我没有安装在能运行PowerShell的系统盘里，因为C盘是默认能运行的我又不会弄其他盘所以我才简略一说。以下是我的经历，你看看我的逻辑有没有什么问题。
既然本项目不适合我，我转投你的相似项目，NoneBot2的官方教材对小白实在不友好，我都不知道怎么打开Python，看了网上其他视频讲解才知道要用PowerShell运行，但是当时我把Python下在E盘哪里都找不到PowerShell，又是一番网上查找才知道C盘才有（另：win11不能直接下载文件到C盘，PowerShell名为终端还TM藏在右键菜单），照着指示一步步做下去最后不知道什么玩意弄出来了，不知道哪里错了，我很崩溃，想想还是回到这里看看算了，然后右下角一行100%Python语言把我弄傻了，然后我把文件移到C盘，成功了。

**Comment by Ljzd-PRO** [comment]
> > > 大佬，我大明白为什么未开始化完成了，我没安装在C盘
> > 
> > 
> > 现在解决了吗？是config.ini文件和main.exe、tool.exe不在同一个目录？要在同一个目录，而可执行文件要在目录下运行的，就是说直接访问双点击打开CM，或者在CM命令来运行的话语，需要在程序目录下执行命令。
> 
> 我不是这个意思，应该这样说，我没有安装在能运行PowerShell的系统盘里，因为C盘是默认能运行的我又不会弄其他盘所以我才简略一说。以下是我的经历，你看看我的逻辑有没有什么问题。 既然本项目不适合我，我转投你的相似项目，NoneBot2的官方教材对小白实在不友好，我都不知道怎么打开Python，看了网上其他视频讲解才知道要用PowerShell运行，但是当时我把Python下在E盘哪里都找不到PowerShell，又是一番网上查找才知道C盘才有（另：win11不能直接下载文件到C盘，PowerShell名为终端还TM藏在右键菜单），照着指示一步步做下去最后不知道什么玩意弄出来了，不知道哪里错了，我很崩溃，想想还是回到这里看看算了，然后右下角一行100%Python语言把我弄傻了，然后我把文件移到C盘，成功了。

确实，如果有图形界面的话会方便些
