### ISSUE TITLE
奇怪的请求报错增加了

### ISSUE THREAD

**Issue by antiaurora** [Ljzd-PRO/Mys_Goods_Tool#79]
{"data":null,"message":"Something went wrong...please retry later","retcode":-502}

**Comment by Ljzd-PRO** [comment]
兑换的是游戏内物品吗？还是实体商品。

**Comment by Ljzd-PRO** [comment]
看一下日志文件

**Comment by antiaurora** [comment]
> 看一下日志文件

因为时间没到，先兑换【万有铺子】满150元减5元优惠券 测试了一下

2023-03-24 14:17:30  程序当前版本: v1.4.4  
2023-03-24 14:17:30  INFO  正在校对互联网时间
2023-03-24 14:17:30  INFO  正在检查商品：2023022415381 的详细信息
2023-03-24 14:17:31  INFO  开始发送商品 2023022415381 的兑换请求...
2023-03-24 14:17:31  INFO  开始发送商品 2023022415381 的兑换请求...
2023-03-24 14:17:31  INFO  开始发送商品 2023022415381 的兑换请求...
2023-03-24 14:17:31  INFO  兑换商品：2023022415381 返回结果：
{"data":null,"message":"Something went wrong...please retry later","retcode":-502}

2023-03-24 14:17:31  INFO  兑换商品：2023022415381 返回结果：
{"data":null,"message":"Something went wrong...please retry later","retcode":-502}

2023-03-24 14:17:31  INFO  商品 2023022415381 兑换失败，可以自行确认。
2023-03-24 14:17:32  INFO  兑换商品：2023022415381 返回结果：
{"data":null,"message":"Something went wrong...please retry later","retcode":-502}

**Comment by Ljzd-PRO** [comment]
> > 看一下日志文件
> 
> 因为时间没到，先兑换【万有铺子】满150元减5元优惠券 测试了一下
> 
> 2023-03-24 14:17:30 程序当前版本: v1.4.4 2023-03-24 14:17:30 INFO 正在校对互联网时间 2023-03-24 14:17:30 INFO 正在检查商品：[2023022415381](tel:2023022415381) 的详细信息 2023-03-24 14:17:31 INFO 开始发送商品 [2023022415381](tel:2023022415381) 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 [2023022415381](tel:2023022415381) 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 [2023022415381](tel:2023022415381) 的兑换请求... 2023-03-24 14:17:31 INFO 兑换商品：[2023022415381](tel:2023022415381) 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> 
> 2023-03-24 14:17:31 INFO 兑换商品：[2023022415381](tel:2023022415381) 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> 
> 2023-03-24 14:17:31 INFO 商品 [2023022415381](tel:2023022415381) 兑换失败，可以自行确认。 2023-03-24 14:17:32 INFO 兑换商品：[2023022415381](tel:2023022415381) 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}

应该是任何时间都可以兑换的吧？那种指定时间开始兑换的商品和不限时间的商品不太一样，要测试指定时间的那种会比较准。

**Comment by antiaurora** [comment]
> > > 看一下日志文件
> > 
> > 
> > 因为时间没到，先兑换【万有铺子】满150元减5元优惠券 测试了一下
> > 2023-03-24 14:17:30 程序当前版本: v1.4.4 2023-03-24 14:17:30 INFO 正在校对互联网时间 2023-03-24 14:17:30 INFO 正在检查商品：2023022415381 的详细信息 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > 2023-03-24 14:17:31 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > 2023-03-24 14:17:31 INFO 商品 2023022415381 兑换失败，可以自行确认。 2023-03-24 14:17:32 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> 
> 应该是任何时间都可以兑换的吧？那种指定时间开始兑换的商品和不限时间的商品不太一样，要测试指定时间的那种会比较准。

行，我下周三再试试(ﾉ´▽｀)ﾉ♪

**Comment by zxyrr** [comment]
兄弟解决了吗

**Comment by zxyrr** [comment]
> > > > 看一下日志文件
> > > 
> > > 
> > > 因为时间没到，先兑换【万有铺子】满150元减5元优惠券 测试了一下
> > > 2023-03-24 14:17:30 程序当前版本: v1.4.4 2023-03-24 14:17:30 INFO 正在校对互联网时间 2023-03-24 14:17:30 INFO 正在检查商品：2023022415381 的详细信息 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > > 2023-03-24 14:17:31 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > > 2023-03-24 14:17:31 INFO 商品 2023022415381 兑换失败，可以自行确认。 2023-03-24 14:17:32 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > 
> > 
> > 应该是任何时间都可以兑换的吧？那种指定时间开始兑换的商品和不限时间的商品不太一样，要测试指定时间的那种会比较准。
> 
> 行，我下周三再试试(ﾉ´▽｀)ﾉ♪

兄弟解决了吗，我这一直接口返回的都是{"data":null,"message":"Something went wrong...please retry later","retcode":-502}

**Comment by antiaurora** [comment]
> > > > > 看一下日志文件
> > > > 
> > > > 
> > > > 因为时间没到，先兑换【万有铺子】满150元减5元优惠券 测试了一下
> > > > 2023-03-24 14:17:30 程序当前版本: v1.4.4 2023-03-24 14:17:30 INFO 正在校对互联网时间 2023-03-24 14:17:30 INFO 正在检查商品：2023022415381 的详细信息 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > > > 2023-03-24 14:17:31 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > > > 2023-03-24 14:17:31 INFO 商品 2023022415381 兑换失败，可以自行确认。 2023-03-24 14:17:32 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > > 
> > > 
> > > 应该是任何时间都可以兑换的吧？那种指定时间开始兑换的商品和不限时间的商品不太一样，要测试指定时间的那种会比较准。
> > 
> > 
> > 行，我下周三再试试(ﾉ´▽｀)ﾉ♪
> 
> 兄弟解决了吗，我这一直接口返回的都是{"data":null,"message":"Something went wrong...please retry later","retcode":-502}

啊哈哈...最近太忙我忘记了，你试过周三的限时物品吗hhhh

**Comment by zxyrr** [comment]
> > > > > > 看一下日志文件
> > > > > 
> > > > > 
> > > > > 因为时间没到，先兑换【万有铺子】满150元减5元优惠券 测试了一下
> > > > > 2023-03-24 14:17:30 程序当前版本: v1.4.4 2023-03-24 14:17:30 INFO 正在校对互联网时间 2023-03-24 14:17:30 INFO 正在检查商品：2023022415381 的详细信息 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > > > > 2023-03-24 14:17:31 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > > > > 2023-03-24 14:17:31 INFO 商品 2023022415381 兑换失败，可以自行确认。 2023-03-24 14:17:32 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > > > 
> > > > 
> > > > 应该是任何时间都可以兑换的吧？那种指定时间开始兑换的商品和不限时间的商品不太一样，要测试指定时间的那种会比较准。
> > > 
> > > 
> > > 行，我下周三再试试(ﾉ´▽｀)ﾉ♪
> > 
> > 
> > 兄弟解决了吗，我这一直接口返回的都是{"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> 
> 啊哈哈...最近太忙我忘记了，你试过周三的限时物品吗hhhh

周三限时抢也是这个问题，返回都是null，并不是OK抢不到。一开始我以为是不是版本号的问题，结果改了依然获取不到数据，不知道哪出问题~

**Comment by antiaurora** [comment]
> > > 看一下日志文件
> > 
> > 
> > 因为时间没到，先兑换【万有铺子】满150元减5元优惠券 测试了一下
> > 2023-03-24 14:17:30 程序当前版本: v1.4.4 2023-03-24 14:17:30 INFO 正在校对互联网时间 2023-03-24 14:17:30 INFO 正在检查商品：2023022415381 的详细信息 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > 2023-03-24 14:17:31 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > 2023-03-24 14:17:31 INFO 商品 2023022415381 兑换失败，可以自行确认。 2023-03-24 14:17:32 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> 
> 应该是任何时间都可以兑换的吧？那种指定时间开始兑换的商品和不限时间的商品不太一样，要测试指定时间的那种会比较准。



> 兑换的是游戏内物品吗？还是实体商品。

大佬康康楼上hhhh

**Comment by zxyrr** [comment]
> > > > 看一下日志文件
> > > 
> > > 
> > > 因为时间没到，先兑换【万有铺子】满150元减5元优惠券 测试了一下
> > > 2023-03-24 14:17:30 程序当前版本: v1.4.4 2023-03-24 14:17:30 INFO 正在校对互联网时间 2023-03-24 14:17:30 INFO 正在检查商品：2023022415381 的详细信息 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 开始发送商品 2023022415381 的兑换请求... 2023-03-24 14:17:31 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > > 2023-03-24 14:17:31 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > > 2023-03-24 14:17:31 INFO 商品 2023022415381 兑换失败，可以自行确认。 2023-03-24 14:17:32 INFO 兑换商品：2023022415381 返回结果： {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> > 
> > 
> > 应该是任何时间都可以兑换的吧？那种指定时间开始兑换的商品和不限时间的商品不太一样，要测试指定时间的那种会比较准。
> 
> > 兑换的是游戏内物品吗？还是实体商品。
> 
> 大佬康康楼上hhhh

是游戏内的，也是指定时间的，依然返回的还是这个结果。为保准确，我也测试了游戏内，指定时间非热门物品；游戏内，指定时间热门物品；实体商品，不限时间物品......接口返回数据都为null，连续好几周了

**Comment by Ljzd-PRO** [comment]
可以尝试一下完全重建的 v2.0.0 https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v2.0.0
