### ISSUE TITLE
v1.4.5的releases只打包了源码，没有打包好的可执行程序吗

### ISSUE THREAD

**Issue by tjzq** [Ljzd-PRO/Mys_Goods_Tool#81]
v1.4.4版本有打包好的程序和源码
![image](https://user-images.githubusercontent.com/110594770/231063453-c3fdf7b6-e3fd-4327-b8c0-011c7f069ff4.png)

**Comment by Ljzd-PRO** [comment]
忘记上传了。这里也有：https://github.com/Ljzd-PRO/Mys_Goods_Tool/actions/runs/4609257015
