### ISSUE TITLE
Alpine-iSH-i686 构建版

### ISSUE THREAD

**Issue by 15059767237** [Ljzd-PRO/Mys_Goods_Tool#83]
Alpine-iSH-i686 构建版这个压缩包在哪里，我根据您给的路径进行跳转后没发现

**Comment by Ljzd-PRO** [comment]
暂时还没有，我找个时间打包一下放上去

**Comment by 15059767237** [comment]
好的，谢谢，等你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ljzd-PRO/Mys_Goods_Tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月26日(星期三) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ljzd-PRO/Mys_Goods_Tool] Alpine-iSH-i686 构建版 (Issue #83)





 
暂时还没有，我找个时间打包一下放上去

**Comment by Ljzd-PRO** [comment]
已上传：https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v1.4.5

**Comment by 15059767237** [comment]
有嘛？大大，在哪里，我怎么找不到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ljzd-PRO/Mys_Goods_Tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月28日(星期五) 上午6:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ljzd-PRO/Mys_Goods_Tool] Alpine-iSH-i686 构建版 (Issue #83)





 
已上传：https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v1.4.5

**Comment by Ljzd-PRO** [comment]
在发行版页面 Assets里。https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/download/v1.4.5/v1.4.5-Alpine.iSH.-i686.zip

**Comment by 15059767237** [comment]
哦哦哦，可以了，谢谢，assets我一直加载不出来,所以一直找不到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ljzd-PRO/Mys_Goods_Tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月28日(星期五) 下午2:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ljzd-PRO/Mys_Goods_Tool] Alpine-iSH-i686 构建版 (Issue #83)





 
在发行版页面 Assets里。https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/download/v1.4.5/v1.4.5-Alpine.iSH.-i686.zip
