### ISSUE TITLE
希望增加星穹铁道

### ISSUE THREAD

**Issue by thz-hub** [Ljzd-PRO/Mys_Goods_Tool#84]
希望增加星穹铁道

**Comment by Canary233** [comment]
同求

**Comment by Ljzd-PRO** [comment]
重写的v2.0.0会支持所有的商品分区，目前在dev分支，还没完成。

**Comment by nyano** [comment]
感谢！mark 等待更新

**Comment by Ljzd-PRO** [comment]
新版本：https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v2.0.0
