### ISSUE TITLE
SSH客户端无法拷贝/跳转人机验证链接

### ISSUE THREAD

**Issue by ytgo** [Ljzd-PRO/Mys_Goods_Tool#88]
用的ssh工具，人机验证链接无法复制。
有个小小建议，可以的话弄一个网页wed界面会比较好弄一点

**Comment by Ljzd-PRO** [comment]
可以暂时通过查看日志文件来复制。网址会输出到日志

**Comment by sagehou** [comment]
可是人机验证监听是localhost，不能通过主机ip访问验证页面
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/26345818/116d1d82-44c4-4290-b2bf-7e1c473000f2)

**Comment by Ljzd-PRO** [comment]
确实应该改成0.0.0.0

**Comment by Ljzd-PRO** [comment]
可以修改`user_data.json`里的地址设置
https://github.com/Ljzd-PRO/Mys_Goods_Tool/blob/0a3acfeb433a7ec2c1d70edb9d59000d562753fb/mys_goods_tool/user_data.py#LL309C12-L309C12

**Comment by sagehou** [comment]
> 可以修改`user_data.json`里的地址设置 https://github.com/Ljzd-PRO/Mys_Goods_Tool/blob/0a3acfeb433a7ec2c1d70edb9d59000d562753fb/mys_goods_tool/user_data.py#LL309C12-L309C12

下次试试，已经本地生成配置了🤭
