### ISSUE TITLE
提前2小时点了开始等待，但是到点没有开始兑换，还是一直等待

### ISSUE THREAD

**Issue by 2375399351** [Ljzd-PRO/Mys_Goods_Tool#92]

**Comment by Ljzd-PRO** [comment]
看一下日志

**Comment by 2375399351** [comment]
> 看一下日志

日志里就没显示运行

**Comment by 2375399351** [comment]
> 看一下日志

只有添加定时任务的记录，接着就只有我测试兑换的记录

**Comment by 2375399351** [comment]
下周再试试吧，这周结束了，看不出什么来

**Comment by Ljzd-PRO** [comment]
是在默认直接打开的终端图形界面里进入兑换模式，还是使用 `-m exchange-simple` 参数进入的兑换模式？

**Comment by Ljzd-PRO** [comment]
我试了一下添加完兑换计划后，手动把商品数据里的时间改成靠近当前的时间，在图形界面和 `exchange-simple` 模式都是可以正常执行兑换的

**Comment by 2375399351** [comment]
> 我试了一下添加完兑换计划后，手动把商品数据里的时间改成靠近当前的时间，在图形界面和 `exchange-simple` 模式都是可以正常执行兑换的

那我再试试看吧，有没有可能是因为电脑黑屏了导致的？因为我电脑开了长时间不动自动关屏幕但是不休眠

**Comment by zzzzzx-1115** [comment]
我刚刚到时间了也没有进行兑换，记录也什么都没有

**Comment by 2375399351** [comment]
> 我刚刚到时间了也没有进行兑换，记录也什么都没有

你也是啊，我还以为是我操作问题……后天再试试看，感觉还是以前的脚本好用

**Comment by Wangxy3** [comment]
我刚刚也是这样的，没有兑换，也没有日志

**Comment by Ljzd-PRO** [comment]
是在什么模式下进入兑换状态的呢？启动时使用 `exchange-simple` 还是在图形界面里点击进入的

**Comment by Wangxy3** [comment]
> 是在什么模式下进入兑换状态的呢？启动时使用 `exchange-simple` 还是在图形界面里点击进入的

图形界面里点击兑换模式的
下午测试兑换之后，等到6点开启脚本，日志就没有变过了

**Comment by Wangxy3** [comment]
> > > 是在什么模式下进入兑换状态的呢？启动时使用 `exchange-simple` 还是在图形界面里点击进入的
> > 
> > 
> > 图形界面里点击兑换模式的
> > ![image](https://user-images.githubusercontent.com/46682624/237383507-10fcc6f8-f349-4889-843b-94ac938179b5.png)
> > 下午测试兑换之后，等到6点开启脚本，日志就没有变过了
> 
> 建议把图片删了……

好了哈哈哈哈

**Comment by 2375399351** [comment]
> > 是在什么模式下进入兑换状态的呢？启动时使用 `exchange-simple` 还是在图形界面里点击进入的
> 
> 
> 
> 图形界面里点击兑换模式的
> 
> 下午测试兑换之后，等到6点开启脚本，日志就没有变过了
> 
> 
> 
> 回复还有的

**Comment by Ljzd-PRO** [comment]
刚才对比了一下，可能是因为用的异步的定时调度器导致的，可能如果在短时间测试（比如30秒后兑换）是没问题的，时间久了就出问题了。
现在改为使用基于线程的定时调度器。

**Comment by Ljzd-PRO** [comment]
可以先用 `exchange-simple` 兑换模式，应该是没什么问题的

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/latest

**Comment by kksjk** [comment]
我也是这个问题，刚刚试了。没用任何日志，但测试兑换就有日志。有日志的都是我测试时的，到18：00啥反应都不行
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/87225356/41aaa14e-c993-4fa1-a44d-30349bf818da)
我用之前的版本就抢到过，感谢大佬
哦，对了，我用的是最新版本了
![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/87225356/52e61889-e89c-4a92-8675-a4bb4c023d8a)

**Comment by Ljzd-PRO** [comment]
相关issue #98
