### ISSUE TITLE
Windows 服务器无法正常显示emoji

### ISSUE THREAD

**Issue by Aellyt** [Ljzd-PRO/Mys_Goods_Tool#93]
首先在我个人电脑上win11系统，开始都是好的，抢过一次后关闭，再次打开界面内鼠标失效了，快捷键都是有效的，管理员运行鼠标就是正常的。还有在服务器上win10系统，好像是不支持的符号还是怎么了，布局什么都都是乱七八糟的
![Uploading 1683284580580.png…]()

**Comment by Aellyt** [comment]
![1683284580580](https://user-images.githubusercontent.com/83526546/236444358-e36d33bc-9a48-4a7e-99a3-7d4a1b124a53.png)

**Comment by Ljzd-PRO** [comment]
可能是和emoji和中文有关

**Comment by Ljzd-PRO** [comment]
如果服务器无法正常显示的话，可以在本地配置好兑换计划以后，把 `user_data.json` 拷贝到服务器，服务器端使用 `-m exchange-simple` 启动参数直接进入兑换模式

**Comment by Ljzd-PRO** [comment]
也可以尝试安装微软官方的Windows Terminal，在Windows 11上是自带的，Windows Server可能也可以安装

**Comment by Aellyt** [comment]
好的，感谢大佬，我试试看，目前我就是自己电脑上配置好复制到服务器上用的
