### ISSUE TITLE
商品兑换中没有大别野的商品

### ISSUE THREAD

**Issue by handlerSam** [Ljzd-PRO/Mys_Goods_Tool#95]
你好，我能看到原神、星穹铁道的商品兑换，但是大别野的商品刷新不出来（我在app上确定是有商品且我的频道等级可以兑换该商品），想问下是没有实现还是程序有问题？

**Comment by Ljzd-PRO** [comment]
确实是程序有问题

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/latest

**Comment by Ljzd-PRO** [comment]
> https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/latest

需要注意 v2.0.1 的米游社分区商品兑换时间是错误的，v2.0.2 修复了
