### ISSUE TITLE
图形界面兑换商品兑换模式还是没有用，到时间还是等待兑换

### ISSUE THREAD

**Issue by xinjioakanai** [Ljzd-PRO/Mys_Goods_Tool#98]

**Comment by Wangxy3** [comment]
看看最新的v2.0.2版本

**Comment by Ljzd-PRO** [comment]
是哪个版本出现的问题呢

**Comment by xinjioakanai** [comment]
我用python安装的v2.0.2

**Comment by 2375399351** [comment]
最新版2.0.2图形版还是不会兑换，感觉还是最老的1.4.4好用，用1.4.4是正常兑换了，作者有没有优化下青龙面板的可能？

**Comment by Wangxy3** [comment]
我的刚刚也没兑换，2.0.2的

**Comment by 2375399351** [comment]
> 我的刚刚也没兑换，2.0.2的

我用的最老的1.4.4是正常兑换了，感觉还是那个稳

**Comment by Wangxy3** [comment]
> > 我的刚刚也没兑换，2.0.2的
> 
> 我用的最老的1.4.4是正常兑换了，感觉还是那个稳

你换的啥，换到了吗

**Comment by 2375399351** [comment]
> > > 我的刚刚也没兑换，2.0.2的
> 
> > 
> 
> > 我用的最老的1.4.4是正常兑换了，感觉还是那个稳
> 
> 
> 
> 你换的啥，换到了吗

换到了，用的1.4.4版本![image](https://github.com/Ljzd-PRO/Mys_Goods_Tool/assets/34334506/589fd94a-675e-44b2-963a-549cfeb024d4)

**Comment by Wangxy3** [comment]
实物还是啥

**Comment by 2375399351** [comment]
> 实物还是啥

星穹

**Comment by Wangxy3** [comment]
> > 实物还是啥
> 
> 星穹

噢噢，我想换那个立牌

**Comment by 2375399351** [comment]
> > > 实物还是啥
> 
> > 
> 
> > 星穹
> 
> 
> 
> 噢噢，我想换那个立牌

下次用1.4.4版本试试看吧

**Comment by Wangxy3** [comment]
> > > > 实物还是啥
> > 
> > 
> > > 
> > 
> > 
> > > 星穹
> > 
> > 
> > 噢噢，我想换那个立牌
> 
> 下次用1.4.4版本试试看吧

好的好的

**Comment by muyuer6** [comment]
的确，2.02图形界面版本操作比较卡，流程也并没有比控制台版本少。最重要的是它不执行兑换，直接等过去了

**Comment by Ljzd-PRO** [comment]
> 最新版2.0.2图形版还是不会兑换，感觉还是最老的1.4.4好用，用1.4.4是正常兑换了，作者有没有优化下青龙面板的可能？

应该可以

**Comment by Ljzd-PRO** [comment]
我这边也做了几次实验，就是添加完兑换计划以后手动修改数据文件里的商品兑换时间戳，几个小时后的兑换计划，确实不会执行。

v2.0.0之前的可以用是因为它是直接用while循环来检查是否到时间了，没有用`apscheduler`

**Comment by Ljzd-PRO** [comment]
从 #101 可以看出原因
https://github.com/Ljzd-PRO/Mys_Goods_Tool/blob/076887477f354ba9b3079385c41ff5d9a7096944/mys_goods_tool/exchange_mode.py#L67-L72
没有 `await`

**Comment by Ljzd-PRO** [comment]
新版本 v2.0.3 应该是成功修复了，我在图形界面下测试了1分钟后的兑换任务是没问题的，另外还挂了Ubuntu 的 图形界面、exchange-simple模式、Windows图形界面，用于测试今天中午12点和真实的晚上7点的兑换计划。

**Comment by Ljzd-PRO** [comment]
> 新版本 v2.0.3 应该是成功修复了，我在图形界面下测试了1分钟后的兑换任务是没问题的，另外还挂了Ubuntu 的 图形界面、exchange-simple模式、Windows图形界面，用于测试今天中午12点和真实的晚上7点的兑换计划。

可以参考：https://github.com/Ljzd-PRO/Mys_Goods_Tool/wiki/Troubleshooting#如何进行测试保证到了兑换时间能够成功执行兑换

**Comment by 2375399351** [comment]
> > 新版本 v2.0.3 应该是成功修复了，我在图形界面下测试了1分钟后的兑换任务是没问题的，另外还挂了Ubuntu 的 图形界面、exchange-simple模式、Windows图形界面，用于测试今天中午12点和真实的晚上7点的兑换计划。
> 
> 
> 
> 可以参考：https://github.com/Ljzd-PRO/Mys_Goods_Tool/wiki/Troubleshooting#如何进行测试保证到了兑换时间能够成功执行兑换

希望可以加个直接删除计划的功能

**Comment by Ljzd-PRO** [comment]
> > > 新版本 v2.0.3 应该是成功修复了，我在图形界面下测试了1分钟后的兑换任务是没问题的，另外还挂了Ubuntu 的 图形界面、exchange-simple模式、Windows图形界面，用于测试今天中午12点和真实的晚上7点的兑换计划。
> > 
> > 
> > 可以参考：[https://github.com/Ljzd-PRO/Mys_Goods_Tool/wiki/Troubleshooting#如何进行测试保证到了兑换时间能够成功执行兑换](https://github.com/Ljzd-PRO/Mys_Goods_Tool/wiki/Troubleshooting#%E5%A6%82%E4%BD%95%E8%BF%9B%E8%A1%8C%E6%B5%8B%E8%AF%95%E4%BF%9D%E8%AF%81%E5%88%B0%E4%BA%86%E5%85%91%E6%8D%A2%E6%97%B6%E9%97%B4%E8%83%BD%E5%A4%9F%E6%88%90%E5%8A%9F%E6%89%A7%E8%A1%8C%E5%85%91%E6%8D%A2)
> 
> 希望可以加个直接删除计划的功能

图形界面下有删除功能的

**Comment by Ljzd-PRO** [comment]
> 最新版2.0.2图形版还是不会兑换，感觉还是最老的1.4.4好用，用1.4.4是正常兑换了，作者有没有优化下青龙面板的可能？

关于这个，感觉提早启动脚本让它等待到了兑换时间再兑换会比较好，而不是到点再启动，因为python启动可能要一点时间，要导入各种包，和那种每日签到什么的情况不一样

**Comment by Ljzd-PRO** [comment]
> 最新版2.0.2图形版还是不会兑换，感觉还是最老的1.4.4好用，用1.4.4是正常兑换了，作者有没有优化下青龙面板的可能？

例如在兑换时间前30分钟执行命令，我还没试过
```shell
./Mys_Goods_Tool -m exchange-simple
```
